<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Start</name>
   <tag></tag>
   <elementGuidId>2d271667-d12e-45d7-873e-651cdbce1f76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__KBFQ735979WQQW7GWOIGNCB8-nx</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='__KBFQ735979WQQW7GWOIGNCB8-nx']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>69fc1a77-9cee-4b78-9098-52c78909e101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__KBFQ735979WQQW7GWOIGNCB8-nx</value>
      <webElementGuid>fc6248e2-db6a-43e5-b206-95b334d9df08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Start Tour</value>
      <webElementGuid>793d9bc6-78f4-4ab9-8d4d-dd47348931ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b07b8c60-6468-4ec7-85f9-bef0237c4ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>help4-start help4-control-button help4-control help4-exposed</value>
      <webElementGuid>1648bc0e-1918-49d1-8b26-9cfc7b2ac222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Start</value>
      <webElementGuid>7b24dac7-9cc0-4354-bbf7-ddb0274875c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__KBFQ735979WQQW7GWOIGNCB8-nx&quot;)</value>
      <webElementGuid>801bb16a-97ee-4276-a472-c4ed923a3015</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='__KBFQ735979WQQW7GWOIGNCB8-nx']</value>
      <webElementGuid>f92ee547-642b-4afc-94ed-6976d3795dde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__KBFQ735979WQQW7GWOIGNCB8']/footer/button[2]</value>
      <webElementGuid>e783de38-3dc1-461a-97ab-e8d7ecc9c9c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>687cd45a-2436-4d07-b596-de0e17f898fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '__KBFQ735979WQQW7GWOIGNCB8-nx' and @title = 'Start Tour' and (text() = 'Start' or . = 'Start')]</value>
      <webElementGuid>1593fc66-926d-4c95-9012-df009de36935</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
