<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Start Guided Tour</name>
   <tag></tag>
   <elementGuidId>e11ce406-cc72-4c4b-bf92-cb86b612b4f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__KBFQ735979WQQW7GWOIGNCB8-cap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='__KBFQ735979WQQW7GWOIGNCB8-cap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>e7b866ce-b4e6-48a5-bc3b-75b91ade489a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__KBFQ735979WQQW7GWOIGNCB8-cap</value>
      <webElementGuid>218b500f-e4cf-43d2-a972-065f58bfe0c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>help4-caption help4-tour</value>
      <webElementGuid>c67b0a1a-8ac5-4112-b8c2-e11ed1904914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Start Guided Tour</value>
      <webElementGuid>e8e2145e-85dc-43a6-b25c-bd420cfeec65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__KBFQ735979WQQW7GWOIGNCB8-cap&quot;)</value>
      <webElementGuid>c3168883-7626-49bd-97a6-dd109c65809f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='__KBFQ735979WQQW7GWOIGNCB8-cap']</value>
      <webElementGuid>c8abdec8-631a-499b-bc64-d0c5e12be861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__KBFQ735979WQQW7GWOIGNCB8']/header/h2</value>
      <webElementGuid>0831ea2c-668f-426f-bd67-74e734c676c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/h2</value>
      <webElementGuid>1703cd71-2ce0-4850-bc95-34e62916a133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = '__KBFQ735979WQQW7GWOIGNCB8-cap' and (text() = 'Start Guided Tour' or . = 'Start Guided Tour')]</value>
      <webElementGuid>d2c97381-6b3d-4d22-9ae7-28c63cfd9da6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
