<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_sapUiIconTitle</name>
   <tag></tag>
   <elementGuidId>b39f06bc-5c45-44b9-ac5a-f5b7131418db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.sapUiIconTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__icon0']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6f40cbf1-9489-4713-9198-389bed8ec66e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Navigation menu</value>
      <webElementGuid>4e92be43-3200-480d-bf95-f68dad98e3f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b0cdf003-c2ea-481b-94c3-3ee6a9c055db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiIconTitle</value>
      <webElementGuid>1ac4462c-4be9-4afa-b9b3-117ae8cdbc04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__icon0&quot;)/span[@class=&quot;sapUiIconTitle&quot;]</value>
      <webElementGuid>dbc3ce77-e860-4014-9d3e-12d6446ab622</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='__icon0']/span</value>
      <webElementGuid>8699e114-7f73-475f-b99c-27fe952bfa0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/span</value>
      <webElementGuid>759fe375-6723-4dc7-bfa1-e140479e9edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Navigation menu']</value>
      <webElementGuid>e67f6d5b-08d0-4531-b28b-ffd9c5246b06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
