<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Manage Production Orders</name>
   <tag></tag>
   <elementGuidId>ec3c22ab-dd72-4b10-a53d-0d55604cb19d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__text100</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__text100']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2602ebaf-14d1-4f67-98f0-c2ee0bf9fca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__text100</value>
      <webElementGuid>eab6297b-70a0-4501-ac64-4b59dfa6e8c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__text100</value>
      <webElementGuid>8a6bbcb6-c410-47a6-9069-1ab343f2a6fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>1b9e8de9-97ae-496b-aa77-46a158dff411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMText sapUiSelectable sapMTextNoWrap sapMTextMaxWidth suggestText suggestNavItem suggestListItemCell</value>
      <webElementGuid>7c800ccf-3443-469f-ae73-598aeb5a9d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manage Production Orders</value>
      <webElementGuid>ecde005c-aa66-4ea2-b0e7-b1206d316414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__text100&quot;)</value>
      <webElementGuid>498ad2cd-d6eb-43c7-8645-59a8d825a7e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__text100']</value>
      <webElementGuid>0b7d5424-2664-4169-95cc-b80477b3b7c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__data964']/span</value>
      <webElementGuid>9369dc24-7ea9-484d-8e50-22ae88b4ad3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/li/div/div/div[2]/span</value>
      <webElementGuid>d9363c7a-3b3d-42d3-8a69-b11a3d34510e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__text100' and (text() = 'Manage Production Orders' or . = 'Manage Production Orders')]</value>
      <webElementGuid>d1fedee8-d8ce-4eb7-a00c-867a5ed97a6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
