<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Create Billing Documents</name>
   <tag></tag>
   <elementGuidId>6aec3f81-3f2b-49d2-a8e3-e86d50e82e4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='Cre­ate Billing Doc­u­ments']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__tile131-title-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>56f44ec7-d8a3-45a1-96e2-9ae74b7f26f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__tile131-title-inner</value>
      <webElementGuid>5c60bd20-fb49-4216-9324-7815b44d946f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMTextMaxLine sapMTextLineClamp</value>
      <webElementGuid>a4fd1da6-471d-4727-bfa8-999d4005ca8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Billing Documents</value>
      <webElementGuid>556ce7b2-c7f6-4324-bd1c-89d3b60ac359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__tile131-title-inner&quot;)</value>
      <webElementGuid>72c6ed90-5c7d-4b94-8c04-883814d4c506</webElementGuid>
   </webElementProperties>
</WebElementEntity>
