<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Manage Sales Orders</name>
   <tag></tag>
   <elementGuidId>830158ca-d765-4fa5-8382-c04108a3de10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__tile124-title-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__tile124-title-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2cca521f-059d-4cd3-a4ca-92a3a5896510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__tile124-title-inner</value>
      <webElementGuid>c5cda04c-ff55-4e12-9e6b-ada068b8d551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMTextMaxLine sapMTextLineClamp</value>
      <webElementGuid>0751da33-806f-46db-92da-1d3092d0abc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manage Sales Orders</value>
      <webElementGuid>a36313b3-365e-4955-977a-1469a02c8908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__tile124-title-inner&quot;)</value>
      <webElementGuid>e5c51848-8e9e-4295-8669-d86022131be2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__tile124-title-inner']</value>
      <webElementGuid>2710c70c-1bae-429b-bbbe-e3f54b90be00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='__tile124-title']/span</value>
      <webElementGuid>29132087-59ec-45ed-b710-c2513b084aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Track Execution'])[1]/following::span[3]</value>
      <webElementGuid>33a7f9b0-633d-418a-8ad5-85883891bd1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales Management Overview'])[1]/following::span[4]</value>
      <webElementGuid>51ed4193-3226-43ff-b80f-50451fa60865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='K'])[3]/preceding::span[4]</value>
      <webElementGuid>9ae4742b-3315-4f0c-8c9c-519b4657ea50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Outbound Deliveries'])[1]/preceding::span[4]</value>
      <webElementGuid>761670be-d1d9-4ceb-8213-423f59f34b74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Manage Sales Orders']/parent::*</value>
      <webElementGuid>6b8ea720-7e0f-4f6d-8f1d-a3ed3cebdc12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[4]/div/div[3]/div/div/div/div/a/div/div/span/span</value>
      <webElementGuid>d5f0ceef-b140-49b8-a292-c1050842ccc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__tile124-title-inner' and (text() = 'Manage Sales Orders' or . = 'Manage Sales Orders')]</value>
      <webElementGuid>476b590c-2340-4988-99b6-196e2122a637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__tile124-title-inner' and (text() = 'Man­age Sales Orders' or . = 'Man­age Sales Orders')]</value>
      <webElementGuid>e751e3c1-f244-46f4-a4d5-47fc8376cdcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
