<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Manage Stock</name>
   <tag></tag>
   <elementGuidId>191ef902-36c6-4847-bd1f-d8173020433e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__tile138-title-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__tile138-title-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8a0fe9f5-c94a-493c-8eeb-627a4d0f13f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__tile138-title-inner</value>
      <webElementGuid>99c099ce-a37e-4427-ae95-83caf0957ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMTextMaxLine sapMTextLineClamp</value>
      <webElementGuid>2a06afc6-18fc-4825-921e-e49a3160777d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manage Stock</value>
      <webElementGuid>4b36cbe0-0703-4698-9671-b2051450d762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__tile138-title-inner&quot;)</value>
      <webElementGuid>2728909b-138a-4d77-b4da-7e366253b09a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__tile138-title-inner']</value>
      <webElementGuid>36c000eb-afb0-4891-adb2-dce1da65bd76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='__tile138-title']/span</value>
      <webElementGuid>8f28bda9-388c-473a-a55a-21e83e4e8272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Single Material'])[1]/following::span[3]</value>
      <webElementGuid>9c8de0c4-dcad-4b12-aa21-c9c7ee1a0050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stock'])[1]/following::span[4]</value>
      <webElementGuid>b9456559-7343-42d2-a8c9-281210d96a9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule Inbound Delivery Creation'])[1]/preceding::span[2]</value>
      <webElementGuid>0edb6585-a9a4-457a-a772-c545db5ccc1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Inbound Deliveries'])[1]/preceding::span[5]</value>
      <webElementGuid>19823927-fcd0-484f-9a98-6a8ecce2b187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Manage Stock']/parent::*</value>
      <webElementGuid>3339cf07-ce6f-4f20-ad1a-4965f5ef1415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[4]/div/div[3]/div/div/div/div/a/div/div/span/span</value>
      <webElementGuid>ba03b223-e65c-4421-9025-47ac0ed8de1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__tile138-title-inner' and (text() = 'Manage Stock' or . = 'Manage Stock')]</value>
      <webElementGuid>ad3526e8-46c7-4a6e-bad4-db42cd43ef36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__tile138-title-inner' and (text() = 'Man­age Stock' or . = 'Man­age Stock')]</value>
      <webElementGuid>fe2b1b3b-dfde-444e-b89c-eb40f81a0222</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
