<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Guided Tours</name>
   <tag></tag>
   <elementGuidId>cf4a3652-9a3d-41fc-8946-d94d350aa96b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__tile189-title-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__tile189-title-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>36795422-f581-4d33-8869-8f932fc69c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__tile189-title-inner</value>
      <webElementGuid>7ec2a6a3-ffc6-4276-8d79-a2df8d482058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMTextMaxLine sapMTextLineClamp</value>
      <webElementGuid>a3dada16-bcd6-40b1-927e-55e83445afa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Guided Tours</value>
      <webElementGuid>02581b71-5a24-48f7-8dd3-88094d3bb212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__tile189-title-inner&quot;)</value>
      <webElementGuid>6ea07f50-f25d-45e3-95bb-0d5bc996a472</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__tile189-title-inner']</value>
      <webElementGuid>52e02ec9-c2c9-4614-be06-cdfba21b29d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='__tile189-title']/span</value>
      <webElementGuid>dd0091f9-e8a5-4ad1-b2a6-47b718f610b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/a/div/div/span/span</value>
      <webElementGuid>a4fef346-94b3-4be3-b6e1-4a0ff99cd4b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__tile189-title-inner' and (text() = 'Guided Tours' or . = 'Guided Tours')]</value>
      <webElementGuid>7de1448a-13d9-4bc9-ba54-a0aab34f62ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
