<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Home</name>
   <tag></tag>
   <elementGuidId>11c92f04-6df8-4eb4-9598-a6e1ced90d7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='shellAppTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.sapUshellAppTitleText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e1a31343-1927-4153-ba99-b14b3d4dea2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUshellAppTitleText</value>
      <webElementGuid>637ac284-d5d1-4705-8b2c-d3ecf95cbf26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>e39a50c0-c903-444e-8a4e-5c2837711c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shellAppTitle-button&quot;)/span[@class=&quot;sapUshellAppTitleText&quot;]</value>
      <webElementGuid>a004a6cd-f452-42a1-a010-cfdd151fc80c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
