<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Post Billing Document</name>
   <tag></tag>
   <elementGuidId>5976c6f2-fb13-491e-889e-0f5e4ff274ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-BillingDocument-manage-component---object--postDocumentButton-BDI-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//bdi[@id='application-BillingDocument-manage-component---object--postDocumentButton-BDI-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>e6e1743e-3a61-4c12-9bb2-6b3fa7f1092b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-BillingDocument-manage-component---object--postDocumentButton-BDI-content</value>
      <webElementGuid>10c10ec6-b1ae-438a-b4fe-0c771767844c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>4d5e264e-51b3-4e4c-94b1-2293de874fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Post Billing Document</value>
      <webElementGuid>b4c236ca-038f-4630-926d-d7ee06591645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-BillingDocument-manage-component---object--postDocumentButton-BDI-content&quot;)</value>
      <webElementGuid>926150a1-4ce5-476a-8e7a-61b4577a85aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='application-BillingDocument-manage-component---object--postDocumentButton-BDI-content']</value>
      <webElementGuid>1f76d49b-09c2-4aea-b610-986ffb54dff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='application-BillingDocument-manage-component---object--postDocumentButton-content']/bdi</value>
      <webElementGuid>e26e8a02-87ad-40ee-8205-bfbe55a6e98b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel Billing Document'])[1]/following::bdi[1]</value>
      <webElementGuid>49be2dda-dd89-46ad-a5c9-3fcd4c4dffc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preview'])[1]/following::bdi[2]</value>
      <webElementGuid>b70b0ff7-ad43-491b-a6c7-f1104a5392ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share'])[2]/preceding::bdi[1]</value>
      <webElementGuid>496de82f-7264-429b-b513-cb4f17e96b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expand Header'])[2]/preceding::bdi[1]</value>
      <webElementGuid>595d4865-d657-4962-8701-26efb226ffb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Post Billing Document']/parent::*</value>
      <webElementGuid>8a26dc06-50b4-49ef-b7e1-0d89a2d7981c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]/span/span/bdi</value>
      <webElementGuid>ff2ebaeb-1be3-4a01-b9d1-dd18ca45fe31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = 'application-BillingDocument-manage-component---object--postDocumentButton-BDI-content' and (text() = 'Post Billing Document' or . = 'Post Billing Document')]</value>
      <webElementGuid>858f9670-1b07-4ad3-abd6-2f631a1119aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
