<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_90204572</name>
   <tag></tag>
   <elementGuidId>324d8051-2e51-45c5-a3bd-16a6750977ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-BillingDocument-manage-component---object--billingDocumentText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='application-BillingDocument-manage-component---object--billingDocumentText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e4ce15bf-2bca-49e1-bdae-79e3dfb718d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-BillingDocument-manage-component---object--billingDocumentText</value>
      <webElementGuid>228d9ef9-8e55-414e-9d17-191ef3b6cfbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-BillingDocument-manage-component---object--billingDocumentText</value>
      <webElementGuid>ea6f40c7-46f6-4f8f-82c4-b0f3a3e14652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>08bb2406-3677-4f11-a6bc-70cca0a62e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMText sapUiSelectable sapMTextBreakWord sapMTextMaxWidth</value>
      <webElementGuid>e9958759-22dd-4964-ab37-8f4f1fef195e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>90204572</value>
      <webElementGuid>c3fd7c3a-1821-4d8b-9592-11cfae5c5902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-BillingDocument-manage-component---object--billingDocumentText&quot;)</value>
      <webElementGuid>37947b43-eafd-488b-8a06-b962f60b3ae6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='application-BillingDocument-manage-component---object--billingDocumentText']</value>
      <webElementGuid>8ce9b031-61a9-447e-bf7f-fb79810bde00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-BillingDocument-manage-component---object--detailObjectPageDynamicHeaderTitle-expand-wrapper']/span</value>
      <webElementGuid>42fc04de-0515-4d8d-9728-ca1a7da61257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share'])[2]/following::span[4]</value>
      <webElementGuid>045e11e4-90a6-44e9-96bb-e871def70cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Post Billing Document'])[1]/following::span[7]</value>
      <webElementGuid>6b10edeb-713f-4a9f-a7c2-b4e9bc2d13e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expand Header'])[2]/preceding::span[3]</value>
      <webElementGuid>bbaff1be-4fb7-4df6-97ca-57ea884b291c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payer'])[1]/preceding::span[4]</value>
      <webElementGuid>7467507d-fa1b-4b6b-984d-c7d0664e482b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/span</value>
      <webElementGuid>6c1ad0f2-f01e-44c9-9b17-70fd571d093c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'application-BillingDocument-manage-component---object--billingDocumentText' and (text() = '90204572' or . = '90204572')]</value>
      <webElementGuid>eb3a4d2d-a33b-4753-867a-e465fa54d9cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
