<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Invoice (F2)</name>
   <tag></tag>
   <elementGuidId>df0e604c-63ba-4bb1-9399-c2d2e29ab342</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Invoice (F2)']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-BillingDocument-manage-component---object--billingDocumentTypeText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f41f1b21-cfab-4f3d-bf22-ea93f1100dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-BillingDocument-manage-component---object--billingDocumentTypeText</value>
      <webElementGuid>fc8aa6d6-d82f-477e-8e22-598266277c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-BillingDocument-manage-component---object--billingDocumentTypeText</value>
      <webElementGuid>544bd4f6-45a7-420a-8d6c-0c527f08e5f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>8c38f58c-e552-455c-9c08-47bd1e9af262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMText sapUiSelectable sapMTextMaxWidth</value>
      <webElementGuid>d027c430-9238-4e6f-8f60-ff8a65ebeed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invoice (F2)</value>
      <webElementGuid>84cd478c-f666-48d1-a5f6-43b01e27c184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-BillingDocument-manage-component---object--billingDocumentTypeText&quot;)</value>
      <webElementGuid>ac3a891c-f32c-4f62-a587-0dac64e2f25e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
