<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Save</name>
   <tag></tag>
   <elementGuidId>7d6d2d7c-d8d6-4c88-a170-21c1070298af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//bdi[text()='Save']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-BillingDocument-manage-component---object--saveButton-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>654f0c26-32ac-47c6-83b6-49d97f50e598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-BillingDocument-manage-component---object--saveButton-inner</value>
      <webElementGuid>6a570db5-bcdf-453c-856a-4705898e3280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMBtnInner sapMBtnHoverable sapMFocusable sapMBtnText sapMBtnEmphasized</value>
      <webElementGuid>ed2670a5-2392-49e6-a4b8-bdc1f9e90795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>3e0f7ca7-6b86-4640-9db2-01f1bf07396b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-BillingDocument-manage-component---object--saveButton-inner&quot;)</value>
      <webElementGuid>f17b7178-4981-4b68-8b3a-e1fe9fd16a49</webElementGuid>
   </webElementProperties>
</WebElementEntity>
