<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Continue</name>
   <tag></tag>
   <elementGuidId>4d62f079-c9f6-4fd2-99df-1ad39900361f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.fn-button__text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='logOnFormSubmit']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9ee4aa33-af14-43ff-bd26-cc6c0306f8f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fn-button__text</value>
      <webElementGuid>84cdb7d5-86df-4842-8b05-887efdbc9a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>83635f1b-30d2-4a94-afea-c246cfd7359d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logOnFormSubmit&quot;)/div[@class=&quot;fn-button__text&quot;]</value>
      <webElementGuid>6dd120c8-c333-4ded-acbf-6758586f6ab1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='logOnFormSubmit']/div</value>
      <webElementGuid>2c81fb37-4720-451a-90b7-cc9e7467304e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>824c263b-8eb2-4dda-906e-80c192525ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>885e5ae6-a06d-480e-8d2b-6d265b37b141</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
