<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_j_username</name>
   <tag></tag>
   <elementGuidId>8952bf45-a893-45f5-b6fc-d3c604f0dc47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#j_username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='j_username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6ac3779-7cc4-4ad1-9dfe-2f5a8d74b6c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5a49eb12-918b-40e4-b4a1-c45973acdde7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fn-input__text-field ids-input ids-input--text ids-input--clear js-has-input-clear js-login-toggle-active-input-user</value>
      <webElementGuid>c76eb81e-7f64-435f-b25f-b9452060b011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>j_username</value>
      <webElementGuid>11b58a72-b7ae-4262-9bb4-0a9905b9e9b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>j_username</value>
      <webElementGuid>6739413c-d3be-476e-82a0-7a49a58677cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>E-Mail, ID, or Login Name</value>
      <webElementGuid>f22fc666-bc28-457d-8fa0-839dae4b32d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a645fa82-2511-4176-ae8c-4ef993d9c4f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j_username&quot;)</value>
      <webElementGuid>8d7f2e56-ae78-4607-8e75-658131ab71ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='j_username']</value>
      <webElementGuid>de913502-a083-4289-a61b-fef7c6c6a1db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='j_username-group']/div[2]/div/div/div/input</value>
      <webElementGuid>86a44c9c-336c-4935-a453-1586035f3a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>d16bf6e0-e0b9-4b17-a52d-3468a6ce0a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'j_username' and @name = 'j_username' and @placeholder = 'E-Mail, ID, or Login Name' and @type = 'text']</value>
      <webElementGuid>6cae4880-23e0-458b-89f9-a3de129fef87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
