<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Create Sales Order</name>
   <tag></tag>
   <elementGuidId>54ea7e58-3c0a-4bdc-b8ef-28efb89d93b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-SalesOrder-manage-component---id-1553605021678-106-originalButtonId-unifiedmenu-txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='application-SalesOrder-manage-component---id-1553605021678-106-originalButtonId-unifiedmenu-txt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>acab8889-db2f-4456-8d12-6ce6e0ede19a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-SalesOrder-manage-component---id-1553605021678-106-originalButtonId-unifiedmenu-txt</value>
      <webElementGuid>ef5eb6e5-c8dd-4a8e-a403-25dd68767649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiMnuItmTxt</value>
      <webElementGuid>17649c4e-4244-42bf-8aa2-facf64ac21b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Sales Order</value>
      <webElementGuid>3e91e3d0-8420-47c3-8f27-d889b56e837f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-SalesOrder-manage-component---id-1553605021678-106-originalButtonId-unifiedmenu-txt&quot;)</value>
      <webElementGuid>f55e383b-0323-472b-932c-3d1c298c04cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='application-SalesOrder-manage-component---id-1553605021678-106-originalButtonId-unifiedmenu-txt']</value>
      <webElementGuid>f5c54f9c-e72d-4546-9c0d-7117a25ce950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='application-SalesOrder-manage-component---id-1553605021678-106-originalButtonId-unifiedmenu']/div[2]</value>
      <webElementGuid>51997944-480b-4c4c-82f8-d6c12a7af7df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Sales Order - VA01'])[1]/following::div[5]</value>
      <webElementGuid>bc71b5fa-8cbf-4f7d-b9ae-e991a627c95a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Category'])[1]/following::div[8]</value>
      <webElementGuid>14628feb-0aae-4d1c-9b9b-677acb254dce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::div[9]</value>
      <webElementGuid>3c5bf590-a482-48e1-add5-ce5b4ce2de09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Sales Orders'])[2]/preceding::div[9]</value>
      <webElementGuid>0206c61a-ff20-49eb-a95a-7b74c8c8daea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create Sales Order']/parent::*</value>
      <webElementGuid>7b0828c4-5f3c-4335-8290-de3b1ccab61f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div[2]</value>
      <webElementGuid>cf51120e-aa59-4340-b066-f78545dd45c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'application-SalesOrder-manage-component---id-1553605021678-106-originalButtonId-unifiedmenu-txt' and (text() = 'Create Sales Order' or . = 'Create Sales Order')]</value>
      <webElementGuid>b191c644-f708-41bf-a3a2-1d59912e03af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
