<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Create Sales Order</name>
   <tag></tag>
   <elementGuidId>24d7a49d-420e-4cce-8087-eb5f6a60a343</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__0005QF358YPGGGV61GZ2SBP5-cap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='__0005QF358YPGGGV61GZ2SBP5-cap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>6cafcec3-45df-420c-8276-17629dfeda82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__0005QF358YPGGGV61GZ2SBP5-cap</value>
      <webElementGuid>73d71981-ad94-45d2-9fae-93a99e7b8f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>help4-caption help4-tour help4-dnd</value>
      <webElementGuid>753d81b3-c9f7-48c9-9999-45b832f0141b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Sales Order</value>
      <webElementGuid>375f055f-5ce6-46a0-8149-87105bfe8044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__0005QF358YPGGGV61GZ2SBP5-cap&quot;)</value>
      <webElementGuid>217e7ebf-24a2-4b53-ad7e-38c3d089360d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='__0005QF358YPGGGV61GZ2SBP5-cap']</value>
      <webElementGuid>2aa25b47-851f-46a8-bbf1-13b0a491cb05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__0005QF358YPGGGV61GZ2SBP5']/header/h2</value>
      <webElementGuid>c43e1b86-8521-409b-b8d2-737926ef7cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/h2</value>
      <webElementGuid>1877e290-4f92-4af7-87e8-290262e087f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = '__0005QF358YPGGGV61GZ2SBP5-cap' and (text() = 'Create Sales Order' or . = 'Create Sales Order')]</value>
      <webElementGuid>912153ce-6278-42b5-b8f2-468f945f6547</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
