<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Create</name>
   <tag></tag>
   <elementGuidId>3d3e3684-f562-4c78-bec1-d9ade6f3c4ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-SalesOrder-manage-component---id-1553605021678-103-internalBtn-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='application-SalesOrder-manage-component---id-1553605021678-103-internalBtn-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dfa64da7-497e-4ba3-98e3-f212748153fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-SalesOrder-manage-component---id-1553605021678-103-internalBtn-inner</value>
      <webElementGuid>f41339a5-6563-4e3b-9216-b183c0ddd99a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMBtnInner sapMBtnHoverable sapMFocusable sapMBtnText sapMBtnDefault</value>
      <webElementGuid>c02c8345-5402-4cfc-b097-42e7ea0a5b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>84c3f8cf-df01-46f6-85d0-7000696438c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-SalesOrder-manage-component---id-1553605021678-103-internalBtn-inner&quot;)</value>
      <webElementGuid>aaaf2f21-cca3-497b-a47e-debe9e762b29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='application-SalesOrder-manage-component---id-1553605021678-103-internalBtn-inner']</value>
      <webElementGuid>40718811-f40e-4207-a4ab-4f4ad1802591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='application-SalesOrder-manage-component---id-1553605021678-103-internalBtn']/span</value>
      <webElementGuid>8f5e5892-cbb7-467c-8907-5f61526b4aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select View'])[2]/following::span[1]</value>
      <webElementGuid>73229398-5b96-4845-89a9-0aa7bdb4a1a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standard'])[2]/following::span[5]</value>
      <webElementGuid>573a8c75-96fb-4563-a456-98d7d7a3393f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create with Reference'])[1]/preceding::span[2]</value>
      <webElementGuid>3b67d50c-f047-4d9b-869d-3972a057f738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[4]/button/span</value>
      <webElementGuid>3c20b7a7-1810-4745-ae7c-8b29db8d58d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'application-SalesOrder-manage-component---id-1553605021678-103-internalBtn-inner' and (text() = 'Create' or . = 'Create')]</value>
      <webElementGuid>034b69f7-8515-4534-b9f8-48976366c161</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
