<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_1026302</name>
   <tag></tag>
   <elementGuidId>ede7ba1c-3348-432a-ba27-a1ff256618b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-ManufacturingOrderItem-manage-component---worklist--idManageOrderWorklistFragment--linkOrder-__clone209</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='application-ManufacturingOrderItem-manage-component---worklist--idManageOrderWorklistFragment--linkOrder-__clone209']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b37c1820-de7a-4011-aaf9-fcdd231289dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-ManufacturingOrderItem-manage-component---worklist--idManageOrderWorklistFragment--linkOrder-__clone209</value>
      <webElementGuid>8585df12-d83b-4862-afd1-899d30b95eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-ManufacturingOrderItem-manage-component---worklist--idManageOrderWorklistFragment--linkOrder-__clone209</value>
      <webElementGuid>5ec9f7f5-359d-4b00-913d-b268cda2f1a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>6974f40e-0b7b-4029-8498-4f005c72a837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9008ec31-4267-4859-8c74-27c11c822c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__text114</value>
      <webElementGuid>09a59e77-6ebe-4f04-b179-9a0d58d988df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMLnk sapMLnkEmphasized sapMLnkMaxWidth</value>
      <webElementGuid>476e57b5-14b3-4e13-8835-5add41cfacb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1026302</value>
      <webElementGuid>8f632581-19f1-4f3e-b634-ffc755422582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-ManufacturingOrderItem-manage-component---worklist--idManageOrderWorklistFragment--linkOrder-__clone209&quot;)</value>
      <webElementGuid>780f8ea4-fd27-4a6e-9355-a2add1d6ecc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='application-ManufacturingOrderItem-manage-component---worklist--idManageOrderWorklistFragment--linkOrder-__clone209']</value>
      <webElementGuid>9e358bb2-ed5d-42d3-a7b9-bf29d755f430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__data1070']/a</value>
      <webElementGuid>84e89332-bd6e-4893-9858-655a47ee465f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'1026302')]</value>
      <webElementGuid>cf7929af-e6ed-4a85-974c-27bc136dc1fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[3]</value>
      <webElementGuid>a9fc1c40-a92b-43c0-96d0-83387816d7e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/a</value>
      <webElementGuid>e9c528a0-221b-4c08-9e4d-955ed1ecba16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'application-ManufacturingOrderItem-manage-component---worklist--idManageOrderWorklistFragment--linkOrder-__clone209' and @href = '#' and (text() = '1026302' or . = '1026302')]</value>
      <webElementGuid>09ff2faa-e781-47b1-8ab6-11c51b386eb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
