<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_I accept all cookies</name>
   <tag></tag>
   <elementGuidId>0bd287fe-7a4d-42a5-88a7-6a7a9c728682</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#truste-consent-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='truste-consent-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6d9fc820-acb5-431a-9e55-d0e50bf9bf13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>truste-consent-button</value>
      <webElementGuid>6ca52950-ba01-4350-947a-a38251fc5913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>636db5f7-462f-4c2b-a866-7c9f906faf87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>truste-button1</value>
      <webElementGuid>6f2dd674-5129-4d23-a35e-d15a5a22cb04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I accept all cookies </value>
      <webElementGuid>b1d39af9-6d29-4135-be3f-caae1dbc3020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;truste-consent-button&quot;)</value>
      <webElementGuid>ac987480-1942-4e9b-90d8-08db2acdf963</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='truste-consent-button']</value>
      <webElementGuid>3933f06f-400d-47b9-9f40-e6ddb5151d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='truste-consent-buttons']/button</value>
      <webElementGuid>0d3a7e8b-610d-4ddf-8175-0fbb56ef03d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/button</value>
      <webElementGuid>9cd763cf-a0f4-4f08-9022-1e7b62c04cb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'truste-consent-button' and @type = 'button' and (text() = 'I accept all cookies ' or . = 'I accept all cookies ')]</value>
      <webElementGuid>68291ddc-8d18-48b8-9fdc-33d02a5182f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
