<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divtrustarc-banner-overlay</name>
   <tag></tag>
   <elementGuidId>c2111695-7c61-4bf5-9103-f8677aa347dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#trustarc-banner-overlay</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='trustarc-banner-overlay']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>16fa757a-cee7-41ad-98c4-3ad247d756b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>trustarc-banner-overlay</value>
      <webElementGuid>2b81ba77-b59a-4f4a-bcdb-f01bfd7e33b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trustarc-banner-overlay&quot;)</value>
      <webElementGuid>e618ab4b-d8fe-43d2-a1c6-64f69111b3f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='trustarc-banner-overlay']</value>
      <webElementGuid>2cd465dc-350c-4f00-8e77-3727a79caa7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='truste-consent-track']/div</value>
      <webElementGuid>f56a1a39-4eaf-44d0-b6b4-e4c1e20d912c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div</value>
      <webElementGuid>df16c277-b91c-4716-89c6-2954899b131e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'trustarc-banner-overlay']</value>
      <webElementGuid>9f80b23a-a410-463c-ad86-d5f2924e34dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
