<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Enter the Customer Reference</name>
   <tag></tag>
   <elementGuidId>7982b7e0-08fb-4840-a719-16c20723115b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--__popover90-messageViewMessageTitleText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dc56639b-8a3d-4642-baa1-d2b4bb5d1c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--__popover90-messageViewMessageTitleText</value>
      <webElementGuid>d8fb7691-e7a1-4690-8f41-dc8d7cdfe9fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--__popover90-messageViewMessageTitleText</value>
      <webElementGuid>40aa4733-5690-4091-be32-a150f916eb6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>f304c324-c840-4cc6-98ff-5fdc52a6cde6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3dadf533-7d99-474f-af37-f78a6140b293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__item177-link</value>
      <webElementGuid>35ebcbe9-cedc-4ac9-862f-b09bb3e02065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMLnk sapMLnkMaxWidth sapMMsgViewTitleText</value>
      <webElementGuid>75f904ca-ad26-4192-846d-c0b66defe56c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enter the Customer Reference.</value>
      <webElementGuid>d87920e2-0598-43d9-ad54-889d97e3a37b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--__popover90-messageViewMessageTitleText&quot;)</value>
      <webElementGuid>8b3ebf27-252e-4680-94df-62c755368ca9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--__popover90-messageViewMessageTitleText']</value>
      <webElementGuid>6ed2e45e-6ab1-4525-825a-3f62c9d0061a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--__popover90-messageView-detailsPage-cont']/a</value>
      <webElementGuid>3b68384c-391a-4b44-9fb6-5dc2b6bab7f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Enter the Customer Reference.')]</value>
      <webElementGuid>27af994e-466d-495d-ad38-ff1c3b905ccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>217cd3a9-03de-4c72-aac5-cceb60ec58a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>70c48bfd-b59e-4442-8f0f-a9faaa9a5603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--__popover90-messageViewMessageTitleText' and @href = '#' and (text() = 'Enter the Customer Reference.' or . = 'Enter the Customer Reference.')]</value>
      <webElementGuid>bb294233-602b-4907-b2ce-e66f97240386</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
