<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Maddison Technologies Corp_1</name>
   <tag></tag>
   <elementGuidId>c643db56-bf8e-4e25-a410-ae7aedca772d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::HeaderFacet::Form::PartnerHeader::DataFieldForAnnotation::_ShipToParty::Contact::Field-content-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>91637b3b-49f0-47a8-ae0d-5ca9cacf7ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::HeaderFacet::Form::PartnerHeader::DataFieldForAnnotation::_ShipToParty::Contact::Field-content-inner</value>
      <webElementGuid>8c87ebed-5582-4252-ad68-7c840f235f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::HeaderFacet::Form::PartnerHeader::DataFieldForAnnotation::_ShipToParty::Contact::Field-content-inner</value>
      <webElementGuid>97c04496-7259-4725-9213-4e23c2a9901a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>da0dda84-4a14-4c98-8afd-c60c76b21378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c21e6a77-a38a-4d21-90e3-4f458381f175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::HeaderFacet::Form::PartnerHeader::DataFieldForAnnotation::_ShipToParty::Contact::Label cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::HeaderFacet::Form::PartnerHeader::DataFieldForAnnotation::_ShipToParty::Contact::Field-content-inner</value>
      <webElementGuid>04170aea-f57e-4e25-b55e-d84ee60ac4e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMLnk sapMLnkMaxWidth</value>
      <webElementGuid>bebb980b-d519-4f48-9138-a8dabb72b32f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Maddison Technologies Corp.</value>
      <webElementGuid>2f200cec-07f7-4423-9f7a-26e5713b8032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::HeaderFacet::Form::PartnerHeader::DataFieldForAnnotation::_ShipToParty::Contact::Field-content-inner&quot;)</value>
      <webElementGuid>68337b80-6a51-47df-a61f-a388a1071fba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::HeaderFacet::Form::PartnerHeader::DataFieldForAnnotation::_ShipToParty::Contact::Field-content-inner']</value>
      <webElementGuid>c5215e2b-5a2d-477e-9087-f8a6029b6ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::HeaderFacet::Form::PartnerHeader::DataFieldForAnnotation::_ShipToParty::Contact::Field-content']/a</value>
      <webElementGuid>a2170b5c-9217-43ec-b0c6-355b076405d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Maddison Technologies Corp.')])[2]</value>
      <webElementGuid>084a00b2-6adc-4cff-ba59-48e764c754bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[93]</value>
      <webElementGuid>47df7a02-caca-42bf-ae01-7e85e141976b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/a</value>
      <webElementGuid>e445a12d-6d15-41cf-9da8-1741381a4217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::HeaderFacet::Form::PartnerHeader::DataFieldForAnnotation::_ShipToParty::Contact::Field-content-inner' and @href = '#' and (text() = 'Maddison Technologies Corp.' or . = 'Maddison Technologies Corp.')]</value>
      <webElementGuid>d78f0f67-f2c1-4b33-9b7b-72eba8c6beec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
