<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Maddison Technologies Corp</name>
   <tag></tag>
   <elementGuidId>8e0d47b7-69e4-4bfd-a2ce-258734d0e93c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::HeaderFacet::Form::PartnerHeader::DataFieldForAnnotation::_SoldToPartyContactInfo::Contact::Field-content-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>98c7dc12-fa03-4c0a-9dfa-edde9f2dbe5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::HeaderFacet::Form::PartnerHeader::DataFieldForAnnotation::_SoldToPartyContactInfo::Contact::Field-content-inner</value>
      <webElementGuid>8acd9785-f223-4843-9598-fdcb327de65f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::HeaderFacet::Form::PartnerHeader::DataFieldForAnnotation::_SoldToPartyContactInfo::Contact::Field-content-inner</value>
      <webElementGuid>e2c9e663-35a8-4ad3-b680-b271539e45e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>3d8aad0c-f84d-4348-9f42-4fb86afd9291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bc2d99eb-e855-4e1b-ab9d-582485b4f1e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::HeaderFacet::Form::PartnerHeader::DataFieldForAnnotation::_SoldToPartyContactInfo::Contact::Label cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::HeaderFacet::Form::PartnerHeader::DataFieldForAnnotation::_SoldToPartyContactInfo::Contact::Field-content-inner</value>
      <webElementGuid>772acd52-0c19-405c-8d4f-d5778340a4e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMLnk sapMLnkMaxWidth</value>
      <webElementGuid>97a08830-0d70-4b66-83a9-430b92576910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Maddison Technologies Corp.</value>
      <webElementGuid>508bb69d-6424-4b2a-8592-535e5321da41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::HeaderFacet::Form::PartnerHeader::DataFieldForAnnotation::_SoldToPartyContactInfo::Contact::Field-content-inner&quot;)</value>
      <webElementGuid>05bcc07b-5d04-47ef-a8e3-9de7a03d0322</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::HeaderFacet::Form::PartnerHeader::DataFieldForAnnotation::_SoldToPartyContactInfo::Contact::Field-content-inner']</value>
      <webElementGuid>800d6375-d0fc-4f39-aa4d-80631c896db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::HeaderFacet::Form::PartnerHeader::DataFieldForAnnotation::_SoldToPartyContactInfo::Contact::Field-content']/a</value>
      <webElementGuid>d99954ab-e7f1-447a-9831-6fed21c300d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Maddison Technologies Corp.')]</value>
      <webElementGuid>b4a02caa-24b0-4544-acd2-27a1547b2198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[92]</value>
      <webElementGuid>cf755aa6-dbda-4fb9-bb12-b63cc56593b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>e8e2c733-ab29-4290-9c08-5913a6ea0ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::HeaderFacet::Form::PartnerHeader::DataFieldForAnnotation::_SoldToPartyContactInfo::Contact::Field-content-inner' and @href = '#' and (text() = 'Maddison Technologies Corp.' or . = 'Maddison Technologies Corp.')]</value>
      <webElementGuid>55688ef9-b9eb-42f9-83ea-6c830779e760</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
