<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Output Items</name>
   <tag></tag>
   <elementGuidId>4840285c-ff54-4236-9d95-7eb0886f0366</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//bdi[@id='cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::ObjectPage-anchBar-cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::FacetSection::OutputItem-anchor-BDI-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>6d5227da-6d6e-40b8-8349-d790aa93bbd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::ObjectPage-anchBar-cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::FacetSection::OutputItem-anchor-BDI-content</value>
      <webElementGuid>7e154bcd-2ec9-44ba-99f8-7ba9f0015dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>91a6f022-d7ec-4b72-b683-ffadc9fb0042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Output Items</value>
      <webElementGuid>482b40a9-f3ee-4463-abc7-e816799f6b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::ObjectPage-anchBar-cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::FacetSection::OutputItem-anchor-BDI-content&quot;)</value>
      <webElementGuid>76e7d310-f816-4dc3-a957-ae9df10cb6fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::ObjectPage-anchBar-cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::FacetSection::OutputItem-anchor-BDI-content']</value>
      <webElementGuid>704d188b-7af2-4a96-a070-bdcf082e7551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::ObjectPage-anchBar-cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::FacetSection::OutputItem-anchor-content']/bdi</value>
      <webElementGuid>c63e3358-6623-44c3-bfdf-a8187359537f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button[4]/span/span/bdi</value>
      <webElementGuid>908884aa-f544-4909-b7c3-61267c21671f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = 'cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::ObjectPage-anchBar-cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::FacetSection::OutputItem-anchor-BDI-content' and (text() = 'Output Items' or . = 'Output Items')]</value>
      <webElementGuid>0f29a582-9777-4163-b9bd-8fa7b0f1fa92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
