<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Incompleteness Info</name>
   <tag></tag>
   <elementGuidId>9f197564-14e1-4c4c-b11f-3c27aa88e065</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//bdi[@id='cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::DataFieldForAction::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.ActivateIncompletenessInfo::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.SalesOrderManageType-BDI-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>5e8a5940-a35a-4ba0-b079-bcd2a62b5280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::DataFieldForAction::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.ActivateIncompletenessInfo::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.SalesOrderManageType-BDI-content</value>
      <webElementGuid>8edefb4d-fa42-49f8-bd7b-6b5a2c17c8d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>33b3da00-7553-4ecd-ac43-c18c0abeac54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Incompleteness Info</value>
      <webElementGuid>feab1630-ea07-4385-902c-51ff3262cdb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::DataFieldForAction::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.ActivateIncompletenessInfo::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.SalesOrderManageType-BDI-content&quot;)</value>
      <webElementGuid>a6a52b24-b816-4198-94bf-cc41d1befde0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::DataFieldForAction::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.ActivateIncompletenessInfo::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.SalesOrderManageType-BDI-content']</value>
      <webElementGuid>bffb0033-4ca3-4153-90de-b9ad09dedcfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::DataFieldForAction::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.ActivateIncompletenessInfo::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.SalesOrderManageType-content']/bdi</value>
      <webElementGuid>22db3f34-8ab0-4172-91f8-87021860324f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/button[2]/span/span/bdi</value>
      <webElementGuid>4b11c628-2e5e-4783-9bef-46985567d101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = 'cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::DataFieldForAction::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.ActivateIncompletenessInfo::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.SalesOrderManageType-BDI-content' and (text() = 'Incompleteness Info' or . = 'Incompleteness Info')]</value>
      <webElementGuid>97560549-5bb6-426c-8e15-b075e5fe8844</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
