<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Close</name>
   <tag></tag>
   <elementGuidId>0a730313-3625-40ba-b865-7216568ef289</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button//*[text()='Close']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__button430-BDI-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>f8c1f5e9-7e08-4c1b-aa41-ff3d3cc69396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__button430-BDI-content</value>
      <webElementGuid>f537b1ce-4a8e-4f61-804d-643157ae5b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>e95a9225-1c59-4411-bfb4-c9431d3cb741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>dbe6216c-4394-4cc9-8480-e8df806e3c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__button430-BDI-content&quot;)</value>
      <webElementGuid>117e7fa8-7dc0-4ce3-bed9-cb5145ea86c6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
