<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Continue</name>
   <tag></tag>
   <elementGuidId>0ad51609-5aa1-4502-b200-21764e91bd03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//bdi[@id='fe::APD_::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.CreateWithSalesOrderType::Action::Ok-BDI-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>0442b30d-e771-428c-a33e-8808fa3c535e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fe::APD_::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.CreateWithSalesOrderType::Action::Ok-BDI-content</value>
      <webElementGuid>45aed5c3-3c98-4152-8909-a73aee1efdcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>f3c43e4d-918f-417d-96d6-98a5ec04419e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>1cc8455d-9aeb-4a01-b61f-889127345ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fe::APD_::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.CreateWithSalesOrderType::Action::Ok-BDI-content&quot;)</value>
      <webElementGuid>0364b9ef-261b-4363-8324-07d0c8c92ef7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='fe::APD_::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.CreateWithSalesOrderType::Action::Ok-BDI-content']</value>
      <webElementGuid>2409eb28-5be5-4512-9083-712fbd6217ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='fe::APD_::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.CreateWithSalesOrderType::Action::Ok-content']/bdi</value>
      <webElementGuid>9e63a127-51ff-49fe-9d5d-6a4ba8ea375d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Division'])[1]/following::bdi[1]</value>
      <webElementGuid>6fd5cc00-5224-4853-9636-51fa7781e8b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Distribution Channel'])[1]/following::bdi[2]</value>
      <webElementGuid>7aa1cbd2-3094-4de7-978b-e775d63eca7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::bdi[1]</value>
      <webElementGuid>d4305ca2-038b-48e8-a1a7-75a26255923c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consignment Fill-Up (CCFU)'])[1]/preceding::bdi[2]</value>
      <webElementGuid>07eb1980-e35c-4bf9-8b1b-ffbac2cff1c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>cdfdcb25-d1a5-42e4-a288-5b74b99f334c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/button/span/span/bdi</value>
      <webElementGuid>81af5006-0e7a-41ef-8a28-a322931af6f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = 'fe::APD_::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.CreateWithSalesOrderType::Action::Ok-BDI-content' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>66f018c6-5ecf-4030-8e7e-7caf28a2574c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/bdi</value>
      <webElementGuid>aa1620cf-09af-4416-9990-6a2ff89c0b87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
