<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Create</name>
   <tag></tag>
   <elementGuidId>c03cf791-c284-4fdf-b234-6d89598c4c41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//bdi[@id='cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::FooterBar::StandardAction::Save-BDI-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>695ab4b2-81fd-4c84-90f9-92908556b3b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::FooterBar::StandardAction::Save-BDI-content</value>
      <webElementGuid>c8544434-043c-4ed7-a066-d39f6b8ecade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>d83743c8-33c3-456a-a350-d2a0f612e13e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>b705a5fc-9d3d-43ca-961b-1ef259ac42af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::FooterBar::StandardAction::Save-BDI-content&quot;)</value>
      <webElementGuid>8f72836e-e6e7-40fc-84ac-cff71f062bbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::FooterBar::StandardAction::Save-BDI-content']</value>
      <webElementGuid>b01f05d2-1530-4d73-b9d6-9640f9e98803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::FooterBar::StandardAction::Save-content']/bdi</value>
      <webElementGuid>f57d1923-60ae-4c2c-9b72-1866997a9f4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show More'])[1]/following::bdi[1]</value>
      <webElementGuid>cea630ab-1c04-4827-894b-6ecdd842696f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Row'])[1]/following::bdi[2]</value>
      <webElementGuid>5a2c6346-47c6-4e6a-ac25-ac60310cbd26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::bdi[1]</value>
      <webElementGuid>7104ba71-96fa-4395-88c4-d1f6019efb82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overdue Receivables'])[1]/preceding::bdi[2]</value>
      <webElementGuid>f6160f71-9212-46eb-b3f4-061e40c68f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create']/parent::*</value>
      <webElementGuid>6c56108f-5e00-480b-89c9-988c8ef1d554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button/span/span/bdi</value>
      <webElementGuid>a6eaca29-41d5-455e-ad1a-dea6a13852f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = 'cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::FooterBar::StandardAction::Save-BDI-content' and (text() = 'Create' or . = 'Create')]</value>
      <webElementGuid>1e4ff9f4-f8c0-45b4-aac5-c6c8f69387f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::table::_BillingPlan::_BillingPlanItem::LineItem::DataFieldForAction::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.CreateBillingPlanItem::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.SalesOrderBillingPlanType-BDI-content']</value>
      <webElementGuid>88dc2302-b8de-49d7-b2f8-f5fcce02a35b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::table::_BillingPlan::_BillingPlanItem::LineItem::DataFieldForAction::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.CreateBillingPlanItem::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.SalesOrderBillingPlanType-content']/bdi</value>
      <webElementGuid>068f01df-1058-4cca-9ccf-d756d31a4e26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/div/div/div/div/button/span/span/bdi</value>
      <webElementGuid>61936de2-6d95-4329-8a5d-bcf259191aaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = 'cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::table::_BillingPlan::_BillingPlanItem::LineItem::DataFieldForAction::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.CreateBillingPlanItem::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.SalesOrderBillingPlanType-BDI-content' and (text() = 'Create' or . = 'Create')]</value>
      <webElementGuid>f3fce0d0-f0a6-4cf2-8528-3405b23dcfe4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
