<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Create_1</name>
   <tag></tag>
   <elementGuidId>690b5e80-78d2-49f9-92d7-89aadd1b9d48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[contains(@id,'fe::APD_::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.CreateBillingPlanItem')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>71310120-a614-4602-9ce3-81bc64c02ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fe::APD_::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.CreateBillingPlanItem::Action::Ok-BDI-content</value>
      <webElementGuid>bfaeef71-f4ac-4144-9bdd-26ecc7e064a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>6b58ea37-766f-4e58-9425-2af245fbfb9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>8d76972b-9c51-4dfc-be35-136b0481c47a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fe::APD_::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.CreateBillingPlanItem::Action::Ok-BDI-content&quot;)</value>
      <webElementGuid>f22e1929-ae2a-4eef-8258-bf1db92e13e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='fe::APD_::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.CreateBillingPlanItem::Action::Ok-BDI-content']</value>
      <webElementGuid>ff47d5df-5252-453c-859e-6d53dba2ca91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='fe::APD_::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.CreateBillingPlanItem::Action::Ok-content']/bdi</value>
      <webElementGuid>fce74a52-579f-4021-878e-f32f116aaaa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/footer/div/button/span/span/bdi</value>
      <webElementGuid>f7b421ca-fb42-4cd0-a3be-eab676ca8538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = 'fe::APD_::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.CreateBillingPlanItem::Action::Ok-BDI-content' and (text() = 'Create' or . = 'Create')]</value>
      <webElementGuid>fb09ea54-7eec-4b2e-9a5d-5a7239fc7768</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
