<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next</name>
   <tag></tag>
   <elementGuidId>db8ad97e-9c1f-435b-b633-b88a1664c325</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__VT4LWMEIPD0FWGRH6TUXH5HS-nx</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='__VT4LWMEIPD0FWGRH6TUXH5HS-nx']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3f5ac4ee-c09a-45e0-b2b3-5dc1985a017a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__VT4LWMEIPD0FWGRH6TUXH5HS-nx</value>
      <webElementGuid>337fdde2-dc49-40e5-8755-aa39d3c338f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Next Tour Step</value>
      <webElementGuid>3eeb8fbf-bfac-4cf5-af7d-744844617eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7e26e2aa-c244-436f-b692-f0ce31cd57ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>help4-next help4-control-button help4-control help4-bubble</value>
      <webElementGuid>ad5363e4-8126-492a-bc5f-a8a47780073d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>422e0f27-27e2-434a-ae6c-535cfb09c0f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__VT4LWMEIPD0FWGRH6TUXH5HS-nx&quot;)</value>
      <webElementGuid>6e4e634b-aab0-4e8b-b6fe-d49b192619b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='__VT4LWMEIPD0FWGRH6TUXH5HS-nx']</value>
      <webElementGuid>69788b70-384d-4fb5-ac72-3ce5fd6ed372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__VT4LWMEIPD0FWGRH6TUXH5HS']/footer/button[2]</value>
      <webElementGuid>8499d32c-4cea-419b-b9b8-d5244fccc2b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/button[2]</value>
      <webElementGuid>25fbe74f-28ae-4605-9765-4f9028f64a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '__VT4LWMEIPD0FWGRH6TUXH5HS-nx' and @title = 'Next Tour Step' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>92ff8052-c691-4c44-8957-ff019cbdd9da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
