<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>circle_sapMRbBInn</name>
   <tag></tag>
   <elementGuidId>a420e3e9-6959-4f7f-bec0-784799592d55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::table::_Partner::LineItem-innerTableRow-__clone507-selectSingle&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>circle.sapMRbBInn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>3c1800f6-ae00-49e8-a8bb-fc515d6b8347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>c9d39008-f996-4c76-9e65-b57f57be426a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMRbBInn</value>
      <webElementGuid>8be17965-e1cb-4a15-b94c-05b1d1ec503d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::table::_Partner::LineItem-innerTableRow-__clone537-selectSingle&quot;)/div[@class=&quot;sapMRbB sapMRbHoverable&quot;]/svg[@class=&quot;sapMRbSvg&quot;]/circle[@class=&quot;sapMRbBInn&quot;]</value>
      <webElementGuid>90d2a850-6854-42e8-a84b-e5f8a5beb619</webElementGuid>
   </webElementProperties>
</WebElementEntity>
