<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Click here to navigate to the external _8f3e74</name>
   <tag></tag>
   <elementGuidId>cf5f3895-52ca-4250-b544-0e99184b53f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::HeaderFacet::KeyFigure::SalesVolumeHeader']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f7e54c3c-4e54-4a6b-9646-edceb3af4fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::HeaderFacet::KeyFigure::SalesVolumeHeader</value>
      <webElementGuid>8e4eb149-3593-4a3f-b07b-30c11c8808f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::HeaderFacet::KeyFigure::SalesVolumeHeader</value>
      <webElementGuid>84f759a5-bd5d-40c7-a752-f17501ed369e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMFlexBox sapMVBox sapMFlexBoxJustifyStart sapMFlexBoxAlignItemsStretch sapMFlexBoxWrapNoWrap sapMFlexBoxAlignContentStretch sapMFlexBoxBGTransparent sapMFlexItem</value>
      <webElementGuid>8b3a9bde-268e-4185-a341-fa352183cbc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Click here to navigate to the external appNet Sales Volume (YTD)0.00 USDObject Number</value>
      <webElementGuid>2d0ed580-b76b-4a66-86da-9902f436fa9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::HeaderFacet::KeyFigure::SalesVolumeHeader&quot;)</value>
      <webElementGuid>461b3d4e-1aba-4c03-8d41-e5768e29f649</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::HeaderFacet::KeyFigure::SalesVolumeHeader']</value>
      <webElementGuid>6feb0c07-839f-4331-933f-cefc3cdf1f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::HeaderFacetContainer::SalesVolumeHeader']/div</value>
      <webElementGuid>04446167-115e-4084-beac-bde0ab883880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div[4]/div</value>
      <webElementGuid>af819f58-514e-4c75-8519-d5b91640fa4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::HeaderFacet::KeyFigure::SalesVolumeHeader' and (text() = 'Click here to navigate to the external appNet Sales Volume (YTD)0.00 USDObject Number' or . = 'Click here to navigate to the external appNet Sales Volume (YTD)0.00 USDObject Number')]</value>
      <webElementGuid>c8474bb7-831c-473e-806c-9f3a05a72dca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
