<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Create Sales Order</name>
   <tag></tag>
   <elementGuidId>18eaac00-4c99-472a-a5c3-92c5f5207b4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__5IL3AFCZBTKA2N4DYE0M6D8E-cap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='__5IL3AFCZBTKA2N4DYE0M6D8E-cap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>43f7e951-bd1c-48aa-9d9a-c8b674117b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__5IL3AFCZBTKA2N4DYE0M6D8E-cap</value>
      <webElementGuid>992acfca-d62f-41fc-929e-68b367dd6770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>help4-caption help4-tour help4-dnd</value>
      <webElementGuid>8f34011f-8883-43ed-a3cb-d4a695fb0edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Sales Order</value>
      <webElementGuid>f44f1093-82c5-4d87-961c-a1e70fccde11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__5IL3AFCZBTKA2N4DYE0M6D8E-cap&quot;)</value>
      <webElementGuid>7e95989f-7430-4ef8-8b86-6ea825f7b79e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='__5IL3AFCZBTKA2N4DYE0M6D8E-cap']</value>
      <webElementGuid>7f3bbc49-db9b-4b0c-97a8-5b26ec31bb05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__5IL3AFCZBTKA2N4DYE0M6D8E']/header/h2</value>
      <webElementGuid>0a7f0d89-f8d2-4d0f-9e77-32654d236288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/h2</value>
      <webElementGuid>59d6de12-b6f7-4540-a970-13544d007be1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = '__5IL3AFCZBTKA2N4DYE0M6D8E-cap' and (text() = 'Create Sales Order' or . = 'Create Sales Order')]</value>
      <webElementGuid>89ffddc3-ba96-4bd3-9fef-c2f7c2102014</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
