<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__shell-header-icon</name>
   <tag></tag>
   <elementGuidId>cae56001-48c9-420c-9f52-ea2636c16f16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#shell-header-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='shell-header-icon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f280a9de-f5e4-4bd5-991f-c589a91f7812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shell-header-icon</value>
      <webElementGuid>05f599a4-b1b8-43b3-a584-4b101079961e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>SAP Logo</value>
      <webElementGuid>d4434509-044e-40a2-9348-70d19ba4c753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ui5.sap.com/1.114.9/resources/sap/ushell/themes/base/img/SAPLogo.svg</value>
      <webElementGuid>0df9b739-b430-4555-80a8-666135901f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shell-header-icon&quot;)</value>
      <webElementGuid>bffb09ab-a574-45dd-a8fe-d5accd1bbaff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='shell-header-icon']</value>
      <webElementGuid>e5b6f664-f737-404c-b9f6-9b6314d104f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='shell-header-logo']/img</value>
      <webElementGuid>1eb5d53b-0fa4-4a14-8012-0aebe04b435f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='SAP Logo']</value>
      <webElementGuid>57623176-8bad-4407-8533-586518b37db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>86229155-f433-45f6-b992-c4d4f377f090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'shell-header-icon' and @alt = 'SAP Logo' and @src = 'https://ui5.sap.com/1.114.9/resources/sap/ushell/themes/base/img/SAPLogo.svg']</value>
      <webElementGuid>380a3af0-a080-4a2f-8d7a-b831640ebe2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
