<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputAPD_SalesOrganization-inner-inner</name>
   <tag></tag>
   <elementGuidId>8038f4de-d02c-4ab9-ab59-ac6b6dd7d762</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='APD_::SalesOrganization-inner-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33b6592a-3f94-4ae0-bcbc-5944a6184cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>APD_::SalesOrganization-inner-inner</value>
      <webElementGuid>8e3b64fa-1dd9-465f-bd9e-d601b4a44dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Dom. Sales Org US (1710)</value>
      <webElementGuid>5450d2a2-ba6e-4ace-ba0d-aeadf0e048a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>APD_::SalesOrganization::Label</value>
      <webElementGuid>8210d254-026f-4cf3-92cb-f70c568f4387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__text83</value>
      <webElementGuid>2d52b73c-e793-417b-9a74-62235509cd35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>05a3767d-5c7e-417f-a067-786b50619123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fe9017c9-f28a-40ac-9cc6-6a2e6f57507f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0741d260-0aec-40f1-938c-a94bd6dcfa43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>329d2fc5-0dec-49fc-a3cb-2549ec7bffe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;APD_::SalesOrganization-inner-inner&quot;)</value>
      <webElementGuid>c1b4f72d-34d4-4ff2-9d69-8abd6185310d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='APD_::SalesOrganization-inner-inner']</value>
      <webElementGuid>e755b995-b2d8-4314-82e8-45647dc377d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='APD_::SalesOrganization-inner-content']/input</value>
      <webElementGuid>df392658-a996-484d-93d9-25cb49186a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>d4d50379-6eb7-415b-9835-39ecb6fa1624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'APD_::SalesOrganization-inner-inner' and @type = 'text']</value>
      <webElementGuid>ae676e45-a1fd-4cd7-b03c-bceebd58cca7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
