<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_New Object___field7-__clone295-__clon_3d7ab8</name>
   <tag></tag>
   <elementGuidId>9799bc84-49be-448c-b8f2-3441cca4fc75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__field7-__clone295-__clone325-inner-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__field7-__clone295-__clone325-inner-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2581c970-4d0c-40b8-8341-b7d087bbb5bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__field7-__clone295-__clone325-inner-inner</value>
      <webElementGuid>6d98ee6e-ed2c-4fa2-a62a-49500c91ae66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__text83</value>
      <webElementGuid>16c831f3-6937-444f-ab05-9b5c37e85e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>7a8d2624-b7eb-4c75-b3a0-5e1fa7e98f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>12451226-f9bf-42bc-ab83-e3555b603427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>266a9684-1a2f-46fa-98f6-e214b4ab6e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>c39355bc-f9c5-4e7d-9994-2a2fbf0daf68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__field7-__clone295-__clone325-inner-inner&quot;)</value>
      <webElementGuid>0880c2e1-65ff-4833-afd1-3f2f0c85c57e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__field7-__clone295-__clone325-inner-inner']</value>
      <webElementGuid>01994221-5837-461f-97e6-2229bc90f655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__field7-__clone295-__clone325-inner-content']/input</value>
      <webElementGuid>c4e253d0-edd0-439e-a7a5-b804c681a6c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div/div/div/input</value>
      <webElementGuid>268f853e-e77a-4aac-ba93-e213ead189d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '__field7-__clone295-__clone325-inner-inner' and @type = 'text']</value>
      <webElementGuid>8910a194-58be-4309-8c20-82e63604ad0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
