<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__field9-__clone451-__clone529-inner-inner</name>
   <tag></tag>
   <elementGuidId>4e20ffc2-2f04-415e-9d24-46c4612b88da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[text()='New Object']/following::td[2]/descendant::*[4]//input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__field9-__clone451-__clone529-inner-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b654a3c-2980-4583-aee6-4001171f88b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__field9-__clone451-__clone529-inner-inner</value>
      <webElementGuid>dc9a8557-58a4-4bba-bd99-1f1e41676df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__text275</value>
      <webElementGuid>2e7d4feb-d950-47e6-8c46-2e9c1e66ead6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f1bfb566-f345-46c3-99c2-31809c44c474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e2579184-02b3-4c1e-8721-32fc01ea19e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>0eb56987-0dbf-4237-a39b-ea40afd5547e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__field9-__clone451-__clone529-inner-inner&quot;)</value>
      <webElementGuid>4a688082-1f3f-4d4b-abd3-08e2a2bfb6c2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
