<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__field7-__clone449-__clone528-inner-inner</name>
   <tag></tag>
   <elementGuidId>d1f4fe64-dd06-4a47-b3cb-c765e3be47c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[text()='New Object']/following::td[1]//input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__field7-__clone449-__clone528-inner-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b3ebcc4-ca8f-4fa1-864e-f3dc4e16653a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__field7-__clone449-__clone528-inner-inner</value>
      <webElementGuid>f6283b7b-4f6f-4f5b-ad45-b29421851117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__text83</value>
      <webElementGuid>3b0fc754-0de1-4af3-be18-2fa267f4b019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>2b625425-0d5d-4294-b811-41c1197abab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e3a1766f-686e-47b7-ad2c-0b354e1050f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>132447a5-cadf-455f-a091-52598514cdc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>659a5023-c940-49be-915b-5fccd3a614b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__field7-__clone449-__clone528-inner-inner&quot;)</value>
      <webElementGuid>75f1b920-3332-4ba0-a8ab-ac6189317c01</webElementGuid>
   </webElementProperties>
</WebElementEntity>
