<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_New Object___field9-__clone297-__clon_de9689</name>
   <tag></tag>
   <elementGuidId>11e8c763-464c-4223-b092-e650a8a687ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__field9-__clone297-__clone326-inner-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__field9-__clone297-__clone326-inner-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b46ec86c-ba7c-4d2b-a589-a3f83429598e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__field9-__clone297-__clone326-inner-inner</value>
      <webElementGuid>58f39695-d03f-49de-aafb-65d187d0cf85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__text451</value>
      <webElementGuid>15ae8896-7c1f-4765-a310-804bd6e9de14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>63eb23e4-80bc-4913-9530-89525d13b6c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>aaf80523-6ffb-480c-9ba0-77675511a170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>0b0b903e-45ac-4d72-89f6-36c21768f823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__field9-__clone297-__clone326-inner-inner&quot;)</value>
      <webElementGuid>c6d020fe-6930-4d22-b9a7-409c803a6e70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__field9-__clone297-__clone326-inner-inner']</value>
      <webElementGuid>2c563f6a-9f4f-49a7-8130-0001f08f9a74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__field9-__clone297-__clone326-inner-content']/input</value>
      <webElementGuid>55dc1a1a-0da1-43c8-bba1-4110e8ff2da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/div/div/div/input</value>
      <webElementGuid>03c11b05-4d70-4910-81ed-2850df75b2fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '__field9-__clone297-__clone326-inner-inner' and @type = 'text']</value>
      <webElementGuid>36437ad6-4816-4cba-886e-b09f42103386</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
