<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>spanAPD_BillingPlanDateCategory-inner-vhi</name>
   <tag></tag>
   <elementGuidId>f8b69241-4675-436a-adb7-f709f575e739</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='APD_::BillingPlanDateCategory-inner-vhi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>36a5ee86-e969-4054-b266-09288fb4d439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>APD_::BillingPlanDateCategory-inner-vhi</value>
      <webElementGuid>88052975-5026-4699-bdf6-5edba3971210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>APD_::BillingPlanDateCategory-inner-vhi</value>
      <webElementGuid>1982e2a8-c7ae-47ab-a32f-0854a681b837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b42a4d07-3a5d-4e5c-9533-cb38cddbe2a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Show Value Help</value>
      <webElementGuid>e878743a-3939-4af1-b95d-7c075daa9fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-icon-content</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>e26b67c6-4d98-43aa-a28f-891a9e09432d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiIcon sapUiIconMirrorInRTL sapUiIconPointer sapMInputBaseIcon</value>
      <webElementGuid>9d860374-b6cc-474d-8498-f4886fc80bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;APD_::BillingPlanDateCategory-inner-vhi&quot;)</value>
      <webElementGuid>8b671605-6736-4ee9-83a5-48b7f5530ee8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='APD_::BillingPlanDateCategory-inner-vhi']</value>
      <webElementGuid>83e643e8-452e-47f9-a9b2-31f4704fcd3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='APD_::BillingPlanDateCategory-inner-content']/div/span</value>
      <webElementGuid>b3814d8d-2c6b-4ee2-bc0d-6ea1fae765b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div/div/div/div/span</value>
      <webElementGuid>8714d9b3-821b-435e-b4bd-a7e36d4d8221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'APD_::BillingPlanDateCategory-inner-vhi']</value>
      <webElementGuid>78233a25-cf1f-4368-b546-8d4b7ccadea3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
