<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Standard Order (OR)</name>
   <tag></tag>
   <elementGuidId>63a3fba7-8143-413a-a19c-f7e9c2c8e7b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__text438-__clone337</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__text438-__clone337']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6f049000-1464-4d6b-9601-2446a5eed884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__text438-__clone337</value>
      <webElementGuid>ed577cca-6b65-463a-bfe4-eb2890b603b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__text438-__clone337</value>
      <webElementGuid>1024761f-f744-4a60-a280-308c5eb8dce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>b6cdd0ce-cd9e-4f20-aa39-6d622e20c3b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMText sapUiSelectable sapMTextMaxWidth sapMTextRenderWhitespaceWrap</value>
      <webElementGuid>9bb83fe3-5deb-4f81-801a-a8f13ae8d894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Standard Order (OR)</value>
      <webElementGuid>9002ff8b-a488-43c1-bc4c-918b6d352e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__text438-__clone337&quot;)</value>
      <webElementGuid>9c203344-2862-49db-8afa-de0f6d25af76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__text438-__clone337']</value>
      <webElementGuid>f3195e13-11d1-4393-b6cc-da01f5a31ef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__wrapper62-__clone337']/span</value>
      <webElementGuid>64893bbb-0da0-4d75-a9f3-bf34a09a12c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ret. Packaging Issue (CCLN)'])[1]/following::span[1]</value>
      <webElementGuid>0f8fa0d4-e484-483c-987b-f5f297c2b105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consignment Issue (CCIS)'])[1]/following::span[2]</value>
      <webElementGuid>331b6e6d-9a53-46fe-b7c9-c76ef26d54c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More'])[1]/preceding::span[1]</value>
      <webElementGuid>3a44efc9-3cba-47ad-a56e-cc49e1aa7f8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::span[4]</value>
      <webElementGuid>5bc4bcd5-fc16-4556-8f52-8f40e17678ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Standard Order (OR)']/parent::*</value>
      <webElementGuid>ebc1675f-57c5-4578-a73c-bff8b91f5ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/div/span</value>
      <webElementGuid>b50fa395-08c1-432e-a7f3-7c843e3b4b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__text438-__clone337' and (text() = 'Standard Order (OR)' or . = 'Standard Order (OR)')]</value>
      <webElementGuid>fdf8bb64-5d8b-4ef4-817f-fb3910f179d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__text322-__clone311']</value>
      <webElementGuid>84fe87af-7d07-46e7-807f-7d012506fa0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__wrapper62-__clone311']/span</value>
      <webElementGuid>41dec6f4-d34b-41df-a587-e038d7395310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__text322-__clone311' and (text() = 'Standard Order (OR)' or . = 'Standard Order (OR)')]</value>
      <webElementGuid>c16ade90-dc36-4aec-8755-e4501996c3b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
