<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_New Sales Order</name>
   <tag></tag>
   <elementGuidId>820310de-138a-4a84-9499-ae5cf9f1f363</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__title1-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__title1-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cf7101e0-47e6-4ccf-adde-b0514a2ba27f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__title1-inner</value>
      <webElementGuid>5fa873cb-c603-484d-931f-1b20021771ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>a86e4150-e8ab-4333-b444-0e1c6c29dd42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New: Sales Order</value>
      <webElementGuid>18faabc0-8168-4467-be1a-236283234562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__title1-inner&quot;)</value>
      <webElementGuid>6a5fcfbf-97e2-4d4f-a4b7-e088c49a07d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__title1-inner']</value>
      <webElementGuid>e64b7fd9-6893-4f71-a9b0-eb1370b55472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h2[@id='__title1']/span</value>
      <webElementGuid>5b055f2e-8de1-4b86-aa1d-8c1b033471c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h2/span</value>
      <webElementGuid>4383411c-1d21-4b1a-ac87-b88a56b92362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__title1-inner' and (text() = 'New: Sales Order' or . = 'New: Sales Order')]</value>
      <webElementGuid>578b44de-1ebe-4671-a94a-87490477000b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
