<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Completed</name>
   <tag></tag>
   <elementGuidId>1d46400c-77bf-437c-a0c8-823c86b5b026</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//*[text()='Completed'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__text242-__clone436-__clone701</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>41b11bc3-bef1-44ac-879d-43627c5504b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__text242-__clone436-__clone701</value>
      <webElementGuid>6c079d44-bc70-4e24-9deb-b6e869b68c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__text242-__clone436-__clone701</value>
      <webElementGuid>4766c7d1-7777-436f-9277-d2e845aea47f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>bcd008f2-6f66-4fb4-a185-b0c1061c2fc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMText sapUiSelectable sapMTextBreakWord sapMTextMaxWidth sapMTextRenderWhitespaceWrap</value>
      <webElementGuid>67d124c1-7337-45ee-a6c5-52b4b29f941f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Completed</value>
      <webElementGuid>fd731469-f0ed-430b-96ce-1f80be1e173a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__text242-__clone436-__clone701&quot;)</value>
      <webElementGuid>304f29e8-363b-4966-80f8-2b452b6e3250</webElementGuid>
   </webElementProperties>
</WebElementEntity>
