<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_206606</name>
   <tag></tag>
   <elementGuidId>67f3c86a-2504-4095-810d-8920cdec2400</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__title1-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__title1-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0f9222f2-2c63-40aa-b1e6-ae75ec7546cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__title1-inner</value>
      <webElementGuid>3b6842fd-d5c1-4302-ba26-ff9479c3f03a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>828f76d4-25b1-48ff-adc6-90056ea6ee07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>206606</value>
      <webElementGuid>d9ce3244-6850-4e9f-8b9b-197857acb5a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__title1-inner&quot;)</value>
      <webElementGuid>035e5fea-6d6e-4fb0-88ff-32e7095b6c99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__title1-inner']</value>
      <webElementGuid>53e18ec3-1d7a-443e-8d32-06aa10581706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h2[@id='__title1']/span</value>
      <webElementGuid>02b55180-a569-4754-bc78-f88bed2ebf69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More'])[1]/following::span[9]</value>
      <webElementGuid>dfcbf5d3-f945-4a98-87fb-739000d43c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[3]/following::span[10]</value>
      <webElementGuid>003d2cd8-39e7-40e4-9caf-5282eec1aaef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/preceding::span[1]</value>
      <webElementGuid>ead0be6f-a5dc-4630-a099-fe9fb548e667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update Prices'])[1]/preceding::span[4]</value>
      <webElementGuid>6d7cdc4a-63ee-4303-8bb2-fb3794c11122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h2/span</value>
      <webElementGuid>92783db8-5f82-47f4-90af-2db7bb931e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__title1-inner' and (text() = '206606' or . = '206606')]</value>
      <webElementGuid>c34619d7-b795-4445-99a0-cf8068e37e9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
