<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_The incompletion check has run. All ne_06be0b</name>
   <tag></tag>
   <elementGuidId>3509fee8-3a1b-4d62-b3fe-9a8ea745cde6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--__popover90-messageViewMessageTitleText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ba03e59a-173f-47b8-af4b-d2d407e3d575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--__popover90-messageViewMessageTitleText</value>
      <webElementGuid>b2e1fb29-3a6f-47c9-a39f-b45fc7b9a13f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--__popover90-messageViewMessageTitleText</value>
      <webElementGuid>4ab42f9b-770e-491d-b462-40f94ecb8852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>fe8c8dba-c338-4aec-993f-93bef847a602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMText sapUiSelectable sapMTextMaxWidth sapMMsgViewTitleText</value>
      <webElementGuid>7a211dda-1b87-4495-ba78-e5abcac5ec41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The incompletion check has run. All necessary data has been provided.</value>
      <webElementGuid>e0f94523-692f-4c39-920d-6a48cd418902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--__popover90-messageViewMessageTitleText&quot;)</value>
      <webElementGuid>e6a8cd3b-d794-42af-b8b6-c92e2e61f8dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--__popover90-messageViewMessageTitleText']</value>
      <webElementGuid>fe4e6005-f463-4f08-802c-250df175b8a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--__popover90-messageView-detailsPage-cont']/span</value>
      <webElementGuid>aff52141-ca96-48ea-b98c-af36332b4a16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/span</value>
      <webElementGuid>826dd0ad-7130-4ec2-b275-68e44e58183b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--__popover90-messageViewMessageTitleText' and (text() = 'The incompletion check has run. All necessary data has been provided.' or . = 'The incompletion check has run. All necessary data has been provided.')]</value>
      <webElementGuid>42b32e59-5033-4727-9d62-1d684efc55be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
