<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_MZ-FG-EB01</name>
   <tag></tag>
   <elementGuidId>cef32b12-833a-4287-876e-91b8ceb941b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='MZ-FG-EB01']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d9a32262-277e-42a3-85f7-c05fe97a37b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputHighlight</value>
      <webElementGuid>d051c3dd-784b-4a1d-bc22-bfe5cb22ede7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MZ-FG-EB01</value>
      <webElementGuid>4394c478-d5ae-4e01-9069-7982c502ac64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__text453-cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::table::_Item::LineItem::TableValueHelp::_Item::Product::Popover::qualifier::::SuggestTable-0&quot;)/span[@class=&quot;sapMInputHighlight&quot;]</value>
      <webElementGuid>33c14e01-7d0c-414d-9b02-539731232681</webElementGuid>
   </webElementProperties>
</WebElementEntity>
