<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_206594</name>
   <tag></tag>
   <elementGuidId>1c923abf-ba93-4723-90c3-05210c17639b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__title1-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__title1-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>42ef6d29-df43-4757-97bc-a3e31e5c79f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__title1-inner</value>
      <webElementGuid>40f839df-5ed9-4c9b-8497-140b6eb4abbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>198c0cbb-4945-42bb-b566-8f8035a511b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>206594</value>
      <webElementGuid>0684f49b-3db6-4bf3-8ad8-64fb901ebe6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__title1-inner&quot;)</value>
      <webElementGuid>35ee4422-54ee-479d-9193-6c651334186d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__title1-inner']</value>
      <webElementGuid>95c5ff38-c484-49e0-9338-7546f2def7d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h2[@id='__title1']/span</value>
      <webElementGuid>24d114c2-1fd4-4774-8451-bc8a3db3d938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h2/span</value>
      <webElementGuid>091e73fb-97f7-4928-ab49-2150a35d90d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__title1-inner' and (text() = '206594' or . = '206594')]</value>
      <webElementGuid>5223b549-d104-4397-bdc8-3146e0c3ffb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
