<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_USCU_S14</name>
   <tag></tag>
   <elementGuidId>e87c9e1f-5a5d-49c7-9a35-23df7492ee5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='USCU_S14']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.sapMInputHighlight</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1fb04c02-c9be-4666-b737-ed07ee16cbec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputHighlight</value>
      <webElementGuid>96a147ee-51d6-48f8-9c8c-4df9696e6b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>USCU_S14</value>
      <webElementGuid>d988b37c-a3d2-4563-96d1-57c42c8e399a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__text440-cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::FormContainer::OrderData::FieldValueHelp::SoldToParty::Popover::qualifier::::SuggestTable-0&quot;)/span[@class=&quot;sapMInputHighlight&quot;]</value>
      <webElementGuid>efd01480-bb5e-4e4e-90ce-a3f9ea2c8deb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
