<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Manage Sales Orders - Version 2</name>
   <tag></tag>
   <elementGuidId>0ad3c7ae-9b68-451e-b516-f6be7a35f16c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__text333</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__text333']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e5a3dc4d-363a-4005-9508-0587bb210f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__text333</value>
      <webElementGuid>290e3401-58ac-4414-8587-bf355cfde500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__text333</value>
      <webElementGuid>b64bb0f9-508c-4b06-a86c-473b539a50e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>d5fee61f-acd4-47ab-9aed-367f946e3360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMText sapUiSelectable sapMTextNoWrap sapMTextMaxWidth suggestText suggestNavItem suggestListItemCell</value>
      <webElementGuid>f5f0f5ad-9e1f-44ed-815a-038c4f8c46e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manage Sales Orders - Version 2</value>
      <webElementGuid>8d4002b6-f9e4-41a5-9fc2-d8a660a210ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__text333&quot;)</value>
      <webElementGuid>6d697c57-5ca7-4d6d-a784-f019f59c057a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__text333']</value>
      <webElementGuid>6419c46a-49a0-4741-8012-6da0308accdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__data2566']/span</value>
      <webElementGuid>48850db1-8c10-4456-ae09-5a9cdd695ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/li/div/div/div[2]/span</value>
      <webElementGuid>9fccb2e2-addf-4336-ad30-4efe1a640dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__text333' and (text() = 'Manage Sales Orders - Version 2' or . = 'Manage Sales Orders - Version 2')]</value>
      <webElementGuid>b86e34e3-11cc-4e70-9827-920c0ec44d4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
