<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_IFRS SFS Test Material 1</name>
   <tag></tag>
   <elementGuidId>0c2434e1-011e-450a-a0eb-58aab3f75d2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[text()='IF11']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>817756ba-493e-47dc-846a-b4ab4e090768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__text279-cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::table::_Item::LineItem::TableValueHelp::_Item::Product::Popover::qualifier::::SuggestTable-0</value>
      <webElementGuid>e7566b5d-6455-4be6-8fa1-d06fd4e65977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__text279-cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::table::_Item::LineItem::TableValueHelp::_Item::Product::Popover::qualifier::::SuggestTable-0</value>
      <webElementGuid>d1ec21df-7942-46db-b0e9-7439e1a44c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>07ec9456-45ba-4e61-b611-b686fe9854c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMText sapUiSelectable sapMTextMaxWidth sapMTextRenderWhitespaceWrap</value>
      <webElementGuid>1567a5aa-c6af-489e-ba4f-9ef3ced33e9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IFRS SFS Test Material 1</value>
      <webElementGuid>c5d59ff9-e8f6-47c3-b776-c18a32e570a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__text279-cus.sd.salesorderv2.manage::SalesOrderManageObjectPage--fe::table::_Item::LineItem::TableValueHelp::_Item::Product::Popover::qualifier::::SuggestTable-0&quot;)</value>
      <webElementGuid>155fbde2-7537-4f2a-ab4c-852ae668dccc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
