<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_80204572</name>
   <tag></tag>
   <elementGuidId>cc61cbb1-26d1-4aae-8dd4-14bd77dd8066</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d1474073-2cb1-4294-9943-1dfd703d7b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i2d.le.st.delivery.log::sap.suite.ui.generic.template.ObjectPage.view.Details::C_CollectiveProcessing--DocumentsTableSDDocumentLink-__clone436</value>
      <webElementGuid>b9444b68-a295-4b1e-972d-683a5edcd4b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>i2d.le.st.delivery.log::sap.suite.ui.generic.template.ObjectPage.view.Details::C_CollectiveProcessing--DocumentsTableSDDocumentLink-__clone436</value>
      <webElementGuid>5b211c18-bc5e-4470-a142-2cc32b3710f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>f2b6dc03-d530-43bb-a3d8-12e7c232f37a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>704b943b-08f6-4bca-bc5a-05038f7652ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>i2d.le.st.delivery.log::sap.suite.ui.generic.template.ObjectPage.view.Details::C_CollectiveProcessing--DeliveryColumnHeaderText i2d.le.st.delivery.log::sap.suite.ui.generic.template.ObjectPage.view.Details::C_CollectiveProcessing--DocumentsTableSDDocumentLink-__clone436</value>
      <webElementGuid>3d1895bf-5075-43c8-90ef-ecb9c91ea14d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMLnk sapMLnkMaxWidth sapUiCompSmartLink</value>
      <webElementGuid>8fdfbc97-d2ca-4132-8bad-3649aeada830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8e261d82-611c-48b8-9af0-6eab800a1102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>80204572</value>
      <webElementGuid>5856bd10-b7c2-41d7-9210-95b8288c72f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i2d.le.st.delivery.log::sap.suite.ui.generic.template.ObjectPage.view.Details::C_CollectiveProcessing--DocumentsTableSDDocumentLink-__clone436&quot;)</value>
      <webElementGuid>f5de97a2-1ed7-40fb-b673-c32bbbc822e2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
