<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_80204572</name>
   <tag></tag>
   <elementGuidId>a434f103-65ea-46f1-b8e1-30ac63b2abdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='i2d.le.st.delivery.log::sap.suite.ui.generic.template.ObjectPage.view.Details::C_CollectiveProcessing--template:::ObjectPageTable:::ColumnListItem:::sFacet::Deliveries::com.sap.vocabularies.UI.v1.LineItem-__clone436_cell0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>0438dd7e-7d61-4185-8e01-1180a8c3295a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i2d.le.st.delivery.log::sap.suite.ui.generic.template.ObjectPage.view.Details::C_CollectiveProcessing--template:::ObjectPageTable:::ColumnListItem:::sFacet::Deliveries::com.sap.vocabularies.UI.v1.LineItem-__clone436_cell0</value>
      <webElementGuid>c70eef0b-1643-4179-9f2a-472e99c7296a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-column</name>
      <type>Main</type>
      <value>i2d.le.st.delivery.log::sap.suite.ui.generic.template.ObjectPage.view.Details::C_CollectiveProcessing--DeliveryForNav</value>
      <webElementGuid>7e0cdf04-73ba-4c45-9aa8-e7f5a841181f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>headers</name>
      <type>Main</type>
      <value>i2d.le.st.delivery.log::sap.suite.ui.generic.template.ObjectPage.view.Details::C_CollectiveProcessing--DeliveryForNav</value>
      <webElementGuid>63bf80bd-2fee-4724-a710-56ecd361fc4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMListTblCell</value>
      <webElementGuid>867c3ba4-e0b8-47fe-b812-9c8ef771265b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>80204572</value>
      <webElementGuid>a977dc25-ac8e-41f8-9f4f-ca7f1b9d04da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i2d.le.st.delivery.log::sap.suite.ui.generic.template.ObjectPage.view.Details::C_CollectiveProcessing--template:::ObjectPageTable:::ColumnListItem:::sFacet::Deliveries::com.sap.vocabularies.UI.v1.LineItem-__clone436_cell0&quot;)</value>
      <webElementGuid>c2fe18bf-249d-4838-8860-0f2c3063725d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='i2d.le.st.delivery.log::sap.suite.ui.generic.template.ObjectPage.view.Details::C_CollectiveProcessing--template:::ObjectPageTable:::ColumnListItem:::sFacet::Deliveries::com.sap.vocabularies.UI.v1.LineItem-__clone436_cell0']</value>
      <webElementGuid>c076d310-897b-4cc6-91b9-667d6ab32d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='i2d.le.st.delivery.log::sap.suite.ui.generic.template.ObjectPage.view.Details::C_CollectiveProcessing--template:::ObjectPageTable:::ColumnListItem:::sFacet::Deliveries::com.sap.vocabularies.UI.v1.LineItem-__clone436']/td[2]</value>
      <webElementGuid>8611f958-7646-4c8f-964a-f670528140ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supplier'])[1]/following::td[2]</value>
      <webElementGuid>c2342f5e-82b6-4ad8-b4f6-9302dca9c596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ship-to Party'])[2]/following::td[2]</value>
      <webElementGuid>caab5d81-f800-4032-b05f-bad675f50405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[1]/preceding::td[1]</value>
      <webElementGuid>637227d5-8ccd-4ec3-9c8f-dfacbb499664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warning issued'])[1]/preceding::td[1]</value>
      <webElementGuid>66a40f3f-f12b-43d8-b426-d0d9b0b210d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/table/tbody/tr/td[2]</value>
      <webElementGuid>990b35ce-4119-40e3-a29c-83712bc3944b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'i2d.le.st.delivery.log::sap.suite.ui.generic.template.ObjectPage.view.Details::C_CollectiveProcessing--template:::ObjectPageTable:::ColumnListItem:::sFacet::Deliveries::com.sap.vocabularies.UI.v1.LineItem-__clone436_cell0' and (text() = '80204572' or . = '80204572')]</value>
      <webElementGuid>3f63c1cd-049f-43db-89d2-cc5eabf6be12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
