<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Share (ShiftCtrlS)</name>
   <tag></tag>
   <elementGuidId>8a1c1a3c-f4fa-4898-86e2-9c7a0f3c847a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='i2d.le.st.delivery.create::sap.suite.ui.generic.template.ListReport.view.ListReport::C_OutboundDeliveryCreate--template:::ListReportPage:::DynamicPageTitle-_actionsToolbar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3c23a8ad-0e38-44f9-87bd-553a7eb7f2b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i2d.le.st.delivery.create::sap.suite.ui.generic.template.ListReport.view.ListReport::C_OutboundDeliveryCreate--template:::ListReportPage:::DynamicPageTitle-_actionsToolbar</value>
      <webElementGuid>dfa8b4c9-f5fd-45ba-924d-b6299929be2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>i2d.le.st.delivery.create::sap.suite.ui.generic.template.ListReport.view.ListReport::C_OutboundDeliveryCreate--template:::ListReportPage:::DynamicPageTitle-_actionsToolbar</value>
      <webElementGuid>ed06decf-1c48-46c4-acb9-a2b211bc06a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-fastnavgroup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ca0a2834-3d5a-4e82-a320-fd0d6fd64900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMIBar sapMTBInactive sapMTB sapMTBNewFlex sapMTBClear sapMTB-Auto-CTX sapMOTB sapFDynamicPageTitleActionsBar</value>
      <webElementGuid>c1f619a6-6f39-4d8e-a5a6-84a8637632c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Share (Shift+Ctrl+S)</value>
      <webElementGuid>b0d11463-2279-4e50-b55d-5091661f5ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i2d.le.st.delivery.create::sap.suite.ui.generic.template.ListReport.view.ListReport::C_OutboundDeliveryCreate--template:::ListReportPage:::DynamicPageTitle-_actionsToolbar&quot;)</value>
      <webElementGuid>18586ed0-2b02-43e0-b9e2-a00ee59d4c62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='i2d.le.st.delivery.create::sap.suite.ui.generic.template.ListReport.view.ListReport::C_OutboundDeliveryCreate--template:::ListReportPage:::DynamicPageTitle-_actionsToolbar']</value>
      <webElementGuid>8813cbc7-dd3b-43a7-a933-b2a644ee6b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i2d.le.st.delivery.create::sap.suite.ui.generic.template.ListReport.view.ListReport::C_OutboundDeliveryCreate--template:::ListReportPage:::DynamicPageTitle-mainActions']/div</value>
      <webElementGuid>4d241834-56f7-44ef-82a0-b93fb53ba32e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select View'])[2]/following::div[3]</value>
      <webElementGuid>cdb99ec3-fee8-4f52-b527-dadc592c067f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[4]</value>
      <webElementGuid>20dc954e-ba52-43b8-ba64-e0a4eddf2b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expand Header'])[1]/preceding::div[5]</value>
      <webElementGuid>774bd20d-4e3e-42cb-9ea1-e1ba1077a0c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/div/div/div[3]/div</value>
      <webElementGuid>58777e10-3ba2-4d3d-b3c6-d09c684fbf0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'i2d.le.st.delivery.create::sap.suite.ui.generic.template.ListReport.view.ListReport::C_OutboundDeliveryCreate--template:::ListReportPage:::DynamicPageTitle-_actionsToolbar' and (text() = 'Share (Shift+Ctrl+S)' or . = 'Share (Shift+Ctrl+S)')]</value>
      <webElementGuid>612796b1-7f21-439f-b4be-9b33e2cd0586</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
