<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Due Up Until Next Week</name>
   <tag></tag>
   <elementGuidId>d4306a7b-d72d-41be-8925-6992438ec029</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='i2d.le.st.delivery.create::sap.suite.ui.generic.template.ListReport.view.ListReport::C_OutboundDeliveryCreate--listReportFilter-filterItemControl_BASIC-DeliveryCreationDate-option-DeliveryCreationDate__custom__DueUpUntilNextWeek-titleText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e5f47b98-2c3c-4c0b-a44a-42de83d91a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i2d.le.st.delivery.create::sap.suite.ui.generic.template.ListReport.view.ListReport::C_OutboundDeliveryCreate--listReportFilter-filterItemControl_BASIC-DeliveryCreationDate-option-DeliveryCreationDate__custom__DueUpUntilNextWeek-titleText</value>
      <webElementGuid>6f49683b-e75b-4746-954e-3f38fcc08815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>072d8abf-3b84-475f-8c86-a5e4a35acdf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Due Up Until Next Week</value>
      <webElementGuid>d4590bc9-ae73-46db-8184-447a944e5356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i2d.le.st.delivery.create::sap.suite.ui.generic.template.ListReport.view.ListReport::C_OutboundDeliveryCreate--listReportFilter-filterItemControl_BASIC-DeliveryCreationDate-option-DeliveryCreationDate__custom__DueUpUntilNextWeek-titleText&quot;)</value>
      <webElementGuid>f5a32141-e3d0-4c24-b71b-5dfd85935b3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='i2d.le.st.delivery.create::sap.suite.ui.generic.template.ListReport.view.ListReport::C_OutboundDeliveryCreate--listReportFilter-filterItemControl_BASIC-DeliveryCreationDate-option-DeliveryCreationDate__custom__DueUpUntilNextWeek-titleText']</value>
      <webElementGuid>6e2f5657-4ad0-4fc2-b906-59614f59d8de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i2d.le.st.delivery.create::sap.suite.ui.generic.template.ListReport.view.ListReport::C_OutboundDeliveryCreate--listReportFilter-filterItemControl_BASIC-DeliveryCreationDate-option-DeliveryCreationDate__custom__DueUpUntilNextWeek-content']/div/div/span</value>
      <webElementGuid>09537a65-bb1c-4c5a-a8d4-3512f0c236ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today and Tomorrow'])[1]/following::span[1]</value>
      <webElementGuid>d454f042-0738-4735-b89a-9f36fcb749d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Group'])[1]/following::span[2]</value>
      <webElementGuid>a4cf3e48-ffdb-4944-b65d-8315099ea3d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Due Up Until Tomorrow'])[1]/preceding::span[1]</value>
      <webElementGuid>cdc5ee5f-c69a-4680-8d86-e3b5d62f0e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::span[6]</value>
      <webElementGuid>2c67b54f-e346-4e6a-b2fd-b35187350f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Due Up Until Next Week']/parent::*</value>
      <webElementGuid>2209a083-f5ae-40eb-b83c-ddc2036d6614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[19]/div/div/div/span</value>
      <webElementGuid>521882fe-0a73-4d73-9a91-e7b517df060b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'i2d.le.st.delivery.create::sap.suite.ui.generic.template.ListReport.view.ListReport::C_OutboundDeliveryCreate--listReportFilter-filterItemControl_BASIC-DeliveryCreationDate-option-DeliveryCreationDate__custom__DueUpUntilNextWeek-titleText' and (text() = 'Due Up Until Next Week' or . = 'Due Up Until Next Week')]</value>
      <webElementGuid>8b2c90b7-1310-4067-8951-6f3c02b94ff9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
