<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Material document 49002556522023 created</name>
   <tag></tag>
   <elementGuidId>0327ee1d-71fe-462e-827c-2e0216840f71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-Material-manageStock-component---S1--idMessage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='application-Material-manageStock-component---S1--idMessage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a96690df-c9bf-41a8-a730-694367583d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-Material-manageStock-component---S1--idMessage</value>
      <webElementGuid>5187067e-a7ce-4ca5-a93f-dfdd682a87f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-Material-manageStock-component---S1--idMessage</value>
      <webElementGuid>96969e33-b87a-490a-bf2b-75a2097d5fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>2535e0c0-4242-42aa-b462-4b14ca633815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>88ba812b-6fea-46af-aac9-f822e2c510f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMLnk sapMLnkMaxWidth</value>
      <webElementGuid>f12090c1-45b3-47e7-89a3-e00e593d5670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Material document 4900255652/2023 created</value>
      <webElementGuid>e666d738-ead3-49f2-a73f-447336d84074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-Material-manageStock-component---S1--idMessage&quot;)</value>
      <webElementGuid>67cb3fa5-e42e-451e-8aa3-f2d2f9358763</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='application-Material-manageStock-component---S1--idMessage']</value>
      <webElementGuid>d9cfc8a5-ceb8-4218-b0c0-47c4cd149738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-Material-manageStock-component---S1--idSuccessPostDialog-scrollCont']/a</value>
      <webElementGuid>57f01cae-127e-4cae-9f03-752685e635b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Material document 4900255652/2023 created')]</value>
      <webElementGuid>3c919b2f-0fd9-478b-8526-4bb4564dedc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>a817fa3e-4971-4f83-80c7-00a09b971f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>d0285d39-7db2-43b9-8968-404e289b5bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'application-Material-manageStock-component---S1--idMessage' and @href = '#' and (text() = 'Material document 4900255652/2023 created' or . = 'Material document 4900255652/2023 created')]</value>
      <webElementGuid>22f775fa-da66-48a5-9579-4d261eea1c3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
