<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_OK</name>
   <tag></tag>
   <elementGuidId>f599942a-4624-4cc9-8094-43284a52a576</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-Material-manageStock-component---S1--idCloseButton-BDI-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//bdi[@id='application-Material-manageStock-component---S1--idCloseButton-BDI-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>e7006a03-43bc-4293-849b-5343dd19c272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-Material-manageStock-component---S1--idCloseButton-BDI-content</value>
      <webElementGuid>40ebd44e-245b-4599-9247-9dd8eebef10e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>e5170c63-fc20-47ad-8d67-f246fcca1ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>6afa5c89-eb76-469b-9dc2-1ca7d71a2e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-Material-manageStock-component---S1--idCloseButton-BDI-content&quot;)</value>
      <webElementGuid>b523023a-1c70-4126-8b98-b42b5a534c4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='application-Material-manageStock-component---S1--idCloseButton-BDI-content']</value>
      <webElementGuid>e94bbbad-22b8-4068-83c7-f0319435154a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='application-Material-manageStock-component---S1--idCloseButton-content']/bdi</value>
      <webElementGuid>d309d043-7e44-4002-85a2-7bd7326bbad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Success'])[1]/following::bdi[1]</value>
      <webElementGuid>b1e43ee2-46bb-4a2a-90f2-60ac53201d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Goods Issue for Cost Center'])[1]/following::bdi[1]</value>
      <webElementGuid>977c36c0-a000-4722-888d-05cabb2f3cb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::bdi[1]</value>
      <webElementGuid>9cfd6bef-9d85-45eb-90dc-7dc7eb5aea62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Stock'])[3]/preceding::bdi[1]</value>
      <webElementGuid>aab89e08-4aab-4e13-9b01-30e8d797260c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>093811d7-2854-418f-abaa-23a69068047f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/footer/div/button/span/span/bdi</value>
      <webElementGuid>c707572e-05ae-4b2a-a0c5-09a5f361982c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = 'application-Material-manageStock-component---S1--idCloseButton-BDI-content' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>6e33f267-91f4-4c2b-a835-dcad4619b091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/footer/div/button/span/span/bdi</value>
      <webElementGuid>6beff4e2-9e91-466e-b1a8-d103575fcf1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
