<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next</name>
   <tag></tag>
   <elementGuidId>424feefb-f46e-420b-b1d2-b4e3b5cdf960</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__ISG0DMLV6HO0UY4823OQI9FF-nx</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='__ISG0DMLV6HO0UY4823OQI9FF-nx']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>60dfbcc2-8df7-4528-9990-9645f98ee1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__ISG0DMLV6HO0UY4823OQI9FF-nx</value>
      <webElementGuid>c77df697-4186-47db-b26c-1a543367f6e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Next Tour Step</value>
      <webElementGuid>cf1beeef-1567-4f62-92c6-bee61c1b5f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2d643ad4-1d9f-46db-b8e3-64b9eb501259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>help4-next help4-control-button help4-control help4-bubble</value>
      <webElementGuid>f49e1f4c-3160-4b06-907e-439805b3967d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>fb0d0ff6-7e82-42a2-80cc-c02174f58ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__ISG0DMLV6HO0UY4823OQI9FF-nx&quot;)</value>
      <webElementGuid>75dd4ecd-7679-4cf6-b3c2-910c34787571</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='__ISG0DMLV6HO0UY4823OQI9FF-nx']</value>
      <webElementGuid>17982ae1-0f9e-4c72-9289-24a00f527f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__ISG0DMLV6HO0UY4823OQI9FF']/footer/button[2]</value>
      <webElementGuid>5c02989d-5392-46a3-85a9-b51a851e6a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/button[2]</value>
      <webElementGuid>a9426986-3dc7-4ec9-9474-d5f94d517313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '__ISG0DMLV6HO0UY4823OQI9FF-nx' and @title = 'Next Tour Step' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>dce5fcb1-2acf-46a3-8afc-2bfc3e9f9972</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
