<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Manage Stock</name>
   <tag></tag>
   <elementGuidId>84abd2b2-be53-4261-92ab-c22a83b0a3e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__ISG0DMLV6HO0UY4823OQI9FF-cap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='__ISG0DMLV6HO0UY4823OQI9FF-cap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>3e4aa9a3-a54d-4e8f-bcaf-3f8dfbd3b579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__ISG0DMLV6HO0UY4823OQI9FF-cap</value>
      <webElementGuid>fbca12c1-a4c2-416d-89ac-f63c3c29e921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>help4-caption help4-tour help4-dnd</value>
      <webElementGuid>0868012b-f349-4177-b812-c0fe85c3d53b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manage Stock</value>
      <webElementGuid>ca216b97-36a2-4cce-b4d4-b2f5cfb91ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__ISG0DMLV6HO0UY4823OQI9FF-cap&quot;)</value>
      <webElementGuid>30aad188-0ca1-4374-a0d2-c84b2e07e4ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='__ISG0DMLV6HO0UY4823OQI9FF-cap']</value>
      <webElementGuid>7e6c6c91-987b-46a7-aaa6-1cb32004bdc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__ISG0DMLV6HO0UY4823OQI9FF']/header/h2</value>
      <webElementGuid>2821a94d-33cf-4378-bf4b-ccd7eefabd4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>dc2b8617-a4c2-42a1-af9f-5ec67bf633f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = '__ISG0DMLV6HO0UY4823OQI9FF-cap' and (text() = 'Manage Stock' or . = 'Manage Stock')]</value>
      <webElementGuid>542d0524-efe3-4e9a-9383-8684910bea7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
