<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>imgshell-header-icon</name>
   <tag></tag>
   <elementGuidId>7e091805-16a0-4faf-a825-bcbc887134ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#shell-header-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='shell-header-icon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0aacc383-3998-47e2-bcd2-5bfa11e02326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shell-header-icon</value>
      <webElementGuid>c0422df2-a8cc-491c-8193-44c97246fe08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>SAP Logo</value>
      <webElementGuid>b2f006b2-21bc-44f3-958a-4f2cf9e9e894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ui5.sap.com/1.114.9/resources/sap/ushell/themes/base/img/SAPLogo.svg</value>
      <webElementGuid>9521246e-6934-455b-85ad-aedd19ee7e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shell-header-icon&quot;)</value>
      <webElementGuid>daddd3bc-172f-4929-b44d-8d2df86274f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='shell-header-icon']</value>
      <webElementGuid>f722805f-7bed-4b2d-a461-3a80301e09b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='shell-header-logo']/img</value>
      <webElementGuid>d3d2c4cc-0ed0-463c-b6e3-f819077dc430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='SAP Logo']</value>
      <webElementGuid>5f3ba704-dd76-4ff1-8bfd-de60f5102845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>1fb54242-3e2d-43f4-8e3a-99a1c8ffa8e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'shell-header-icon' and @alt = 'SAP Logo' and @src = 'https://ui5.sap.com/1.114.9/resources/sap/ushell/themes/base/img/SAPLogo.svg']</value>
      <webElementGuid>85261b34-a6fc-40bc-967e-3bb34c527160</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
