<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputidInputQuantity-input-inner</name>
   <tag></tag>
   <elementGuidId>6889f342-13b5-461b-aa54-d2642b8fab57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#idInputQuantity-input-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='idInputQuantity-input-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bded50b9-854b-4122-a81a-34358b84e961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idInputQuantity-input-inner</value>
      <webElementGuid>30f6bd0a-cefb-4938-9b72-cbe05178d96d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.000</value>
      <webElementGuid>489ff60e-ff1c-459c-8f01-37c171c640be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>486ef889-dad9-475b-9b75-84a37ff2dee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>spinbutton</value>
      <webElementGuid>0152737d-50ef-4d02-be05-48b65978d4b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>09e409c4-5277-45cf-8364-9c338e52dacd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-errormessage</name>
      <type>Main</type>
      <value>idInputQuantity-input-message-sr</value>
      <webElementGuid>a878b97c-ad64-4c01-997c-9a24b5d8156a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuenow</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>296b59aa-73fb-4738-8d64-cae76362e612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuetext</name>
      <type>Main</type>
      <value>0.000</value>
      <webElementGuid>24d507f0-62a6-4d51-9e90-3aeb2dc158c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemin</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>571dab62-e142-41a5-a3d7-445ada44d074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemax</name>
      <type>Main</type>
      <value>9999999999999</value>
      <webElementGuid>7c4deaf8-e16b-47c6-9c1a-db54a716efc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>idInputQuantityLabel</value>
      <webElementGuid>c29eccf5-795a-4fd3-aa45-1ba12ba00654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ac21c85a-57d7-47e0-9011-dae8f021f3d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>b4e87286-06e5-414f-a0b0-cd5e43f42c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idInputQuantity-input-inner&quot;)</value>
      <webElementGuid>001e0723-ae74-4185-97fa-741ee7fbd948</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='idInputQuantity-input-inner']</value>
      <webElementGuid>2d085599-f567-4a13-945a-ada9cf6c6ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idInputQuantity-input-content']/input</value>
      <webElementGuid>ba37afe6-a9d7-48f4-ba74-c163dcb81005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>038d4fb1-75b5-4824-814d-fffbed35352f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'idInputQuantity-input-inner' and @type = 'text']</value>
      <webElementGuid>ef44bba1-5102-4c1c-995f-8ab154ab22f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
