<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputapplication-Material-manageStock-compo_1a22d7</name>
   <tag></tag>
   <elementGuidId>db5844e8-60c9-4489-bd34-908916c60de5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-Material-manageStock-component---S1--idMaterialInput-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='application-Material-manageStock-component---S1--idMaterialInput-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fc5e2d35-8b8a-40ff-805e-4882fac8d2c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-Material-manageStock-component---S1--idMaterialInput-inner</value>
      <webElementGuid>fd22ae38-1630-4813-8a6f-a2d519049c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>application-Material-manageStock-component---S1--idFormElementMaterial-label</value>
      <webElementGuid>ba42f273-d0dc-4621-9aae-c986dfc783ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>85ce170f-1cf2-4845-9eb4-f677cc8d0c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e5aaa79b-cddb-42bb-8b29-1db39b7c8687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d4b9662a-3b50-4b77-b480-29afb13735e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>8703c045-7399-4776-b4b7-ac2ea6e5dbad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__text83</value>
      <webElementGuid>9bda646e-fb27-4b97-abf7-f6ada01eab12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-Material-manageStock-component---S1--idMaterialInput-inner&quot;)</value>
      <webElementGuid>98172d70-0faf-4699-919e-a8febd424f6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='application-Material-manageStock-component---S1--idMaterialInput-inner']</value>
      <webElementGuid>633a3a15-9d17-49f6-bc77-cace164ffa03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-Material-manageStock-component---S1--idMaterialInput-content']/input</value>
      <webElementGuid>44817dd2-8ca9-41f7-9ed5-a58b735ff0cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>12ecf268-0c93-4241-8237-0a43fcfda6dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'application-Material-manageStock-component---S1--idMaterialInput-inner' and @type = 'text']</value>
      <webElementGuid>e4052037-ed29-4dcc-b335-686c75275c60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
