<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Initial Entry</name>
   <tag></tag>
   <elementGuidId>54847d63-594c-49c9-8599-75d625756c0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#idSelItemStkTyp-idManageStockType-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='idSelItemStkTyp-idManageStockType-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>6bfe24d8-54d5-4170-8996-27bec6621a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idSelItemStkTyp-idManageStockType-0</value>
      <webElementGuid>15c5508f-e007-4315-be39-2f5fc6343575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>idSelItemStkTyp-idManageStockType-0</value>
      <webElementGuid>9690a1f7-2622-4d4d-981f-093153d86de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a15457e7-878f-4253-ab41-fa7ef40bd957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f590212c-b144-4e7e-955f-1fdcf429c9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>af49f903-4690-40e4-9afd-ca4eb2ed70ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>72be467f-6157-47ed-b161-cb09900b41d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f4a96ad0-ed1a-4532-8399-cc711745f557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMSelectListItemBase sapMSelectListItem sapMSelectListItemBaseHoverable sapMSelectListItemBaseSelected sapMSelectListItemBasePressed</value>
      <webElementGuid>35f33586-6d5c-4daf-9e01-5bb64ff09fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Initial Entry</value>
      <webElementGuid>bb7b46a8-6d6b-4443-b364-f6d0a158cd20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idSelItemStkTyp-idManageStockType-0&quot;)</value>
      <webElementGuid>231cb815-8f2f-4e31-b017-8d562af4d05d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='idSelItemStkTyp-idManageStockType-0']</value>
      <webElementGuid>3a7d6e8e-7c54-4c76-89f9-0e5c3d9d3d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='__list16']/li</value>
      <webElementGuid>6f291229-2a5c-49e0-b19b-da96f923a3d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select your manage stock operation'])[2]/following::li[1]</value>
      <webElementGuid>a95d3a41-2268-4145-9515-e8b6b075abfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::li[1]</value>
      <webElementGuid>8561150c-f275-4e85-bff3-7afca25e96f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scrapping'])[2]/preceding::li[1]</value>
      <webElementGuid>6507c97e-9962-42d3-a7c7-9f7c68f0b711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Goods Issue for Cost Center'])[2]/preceding::li[2]</value>
      <webElementGuid>69414f86-832a-4e66-a433-adc236b4be26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/ul/li</value>
      <webElementGuid>95f5d9d4-b8d0-4209-be22-b08b6a7a0730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'idSelItemStkTyp-idManageStockType-0' and (text() = 'Initial Entry' or . = 'Initial Entry')]</value>
      <webElementGuid>b9125925-2314-40bf-bc5f-df3bd01c2b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='__list10']/li</value>
      <webElementGuid>b44524bc-51a2-48be-a142-b05cb888c821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/ul/li</value>
      <webElementGuid>15c4c047-8f15-456b-88bd-c62736dc1899</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
