<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select Options</name>
   <tag></tag>
   <elementGuidId>19ee0961-86c3-4218-bf5f-04d60dbf8849</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-Material-manageStock-component---S1--idselectPlant-arrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='application-Material-manageStock-component---S1--idselectPlant-arrow']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d797db64-f0a7-4e36-bd0d-326dc3cc0693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-Material-manageStock-component---S1--idselectPlant-arrow</value>
      <webElementGuid>289bf798-8cff-4e97-af73-6d0c1d144e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-Material-manageStock-component---S1--idselectPlant-arrow</value>
      <webElementGuid>6aa23590-e882-4f77-8a91-cc5987a3aec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>application-Material-manageStock-component---S1--idFormElementPlant-label application-Material-manageStock-component---S1--idselectPlant-arrow-label</value>
      <webElementGuid>d6b414dc-90f5-4181-9295-7e05d55c7c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>87d79078-dfa9-4a27-bccd-1e1eb58cc100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-icon-content</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>64457a6e-8e6d-4aa4-b774-178a2239398a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiIcon sapUiIconMirrorInRTL sapUiIconPointer sapMInputBaseIcon</value>
      <webElementGuid>b8e19c77-8854-4ade-bebc-166ffa411ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Options</value>
      <webElementGuid>1de2aed2-558c-4f7f-97bb-598445b12c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-Material-manageStock-component---S1--idselectPlant-arrow&quot;)</value>
      <webElementGuid>91bdd363-af51-452b-8a1e-fcbea5a6a113</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='application-Material-manageStock-component---S1--idselectPlant-arrow']</value>
      <webElementGuid>c36195a1-923b-4cb4-968e-683d0bb12c81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-Material-manageStock-component---S1--idselectPlant-content']/div/span</value>
      <webElementGuid>212f23e0-5b13-440b-b194-9b7c834616ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plant'])[1]/following::span[2]</value>
      <webElementGuid>b2811b24-9356-4c54-ad99-93dbaca24526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scan'])[2]/following::span[3]</value>
      <webElementGuid>1e684a16-9547-402a-90d4-a48b59db5389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share'])[1]/preceding::span[4]</value>
      <webElementGuid>cb689e1c-8014-4048-bab0-0a2550b78177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expand Header'])[1]/preceding::span[9]</value>
      <webElementGuid>db3d1f33-a20f-46a0-8c98-09dc4b7e9be0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/span</value>
      <webElementGuid>e36e5345-eb6b-4b4e-8637-b4a14171649b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'application-Material-manageStock-component---S1--idselectPlant-arrow' and (text() = 'Select Options' or . = 'Select Options')]</value>
      <webElementGuid>b3e7c3d2-3a5e-4242-8be4-b3071a8c9adb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
