<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_MZ-FG-EB0</name>
   <tag></tag>
   <elementGuidId>f02cc26d-1a1f-4bc0-9cae-6baea937395e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__label30-application-Material-manageStock-component---S1--idMaterialInput-0 > span.sapMInputHighlight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__label30-application-Material-manageStock-component---S1--idMaterialInput-0']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>64d4177c-f1f1-4a37-9734-26676df1d1be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputHighlight</value>
      <webElementGuid>660e8bd0-b390-4464-a7be-ca8ca55acf71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MZ-FG-EB0</value>
      <webElementGuid>8a685806-79bc-4861-8659-c58b7b614ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__label30-application-Material-manageStock-component---S1--idMaterialInput-0&quot;)/span[@class=&quot;sapMInputHighlight&quot;]</value>
      <webElementGuid>1ea9eba3-6a0f-4ad8-afed-c7e3bf2f856e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='__label30-application-Material-manageStock-component---S1--idMaterialInput-0']/span</value>
      <webElementGuid>14a24f7b-a217-4daa-bbc9-a945db631287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/span/span</value>
      <webElementGuid>e045b692-bba0-4b54-9af9-95a5cdef5f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'MZ-FG-EB0' or . = 'MZ-FG-EB0')]</value>
      <webElementGuid>b6955fc0-abb7-44b6-bb5b-7c011dafd6df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
