<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Initial Entry</name>
   <tag></tag>
   <elementGuidId>0f698e27-7271-40fc-837d-8054f765c801</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#idManageStockType-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='idManageStockType-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3e286ea8-6433-4db2-b94a-4d926c11d58c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idManageStockType-label</value>
      <webElementGuid>09f8aac7-ec9c-4b02-9a21-c68917b5a9c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a878c5c3-e9cf-4355-96bd-f46f0cf2b025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMSltLabel sapMSltLabelState sapMSltLabelInformation</value>
      <webElementGuid>3408c584-b661-4e97-bed7-e7959f9cfa91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Initial Entry</value>
      <webElementGuid>6314fe7b-ada7-42ea-ac62-d19e4d7723ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idManageStockType-label&quot;)</value>
      <webElementGuid>6d58c542-8b46-4da9-839e-07136f49ad5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='idManageStockType-label']</value>
      <webElementGuid>5064fdda-2463-4ef4-829c-444ae6fe0e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idManageStockType']/span</value>
      <webElementGuid>5232a314-f48f-4fda-ac68-69686e5ebde0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span</value>
      <webElementGuid>7401be41-5374-40e6-9083-36e8c77d2eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'idManageStockType-label' and (text() = 'Initial Entry' or . = 'Initial Entry')]</value>
      <webElementGuid>75251899-064c-4d19-a9a6-6aaaec060203</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
