<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>spanapplication-Material-manageStock-compon_cca482</name>
   <tag></tag>
   <elementGuidId>016b3a4d-d10b-4a1e-bfb8-1542828a8620</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-Material-manageStock-component---S1--idCurrentStockButton-application-Material-manageStock-component---S1--idStorageLocationTable-0-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='application-Material-manageStock-component---S1--idCurrentStockButton-application-Material-manageStock-component---S1--idStorageLocationTable-0-img']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0ebf0c2e-a623-46c7-a356-d527fce7496a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-Material-manageStock-component---S1--idCurrentStockButton-application-Material-manageStock-component---S1--idStorageLocationTable-0-img</value>
      <webElementGuid>d538bfe1-6194-427a-803e-5dce3c9cb98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-Material-manageStock-component---S1--idCurrentStockButton-application-Material-manageStock-component---S1--idStorageLocationTable-0-img</value>
      <webElementGuid>be8d5717-f965-46cb-99a5-e6766a938691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>7456d896-cf38-448d-9540-12af9fe2185a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5037ad55-c8ac-49cc-95be-16d20cefa5c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-icon-content</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>d46484e0-75c5-4941-bdfa-3035e5d647fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiIcon sapMBtnCustomIcon sapMBtnIcon sapMBtnIconLeft</value>
      <webElementGuid>f4417372-081c-4121-83ef-d8f0e8c63bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-Material-manageStock-component---S1--idCurrentStockButton-application-Material-manageStock-component---S1--idStorageLocationTable-0-img&quot;)</value>
      <webElementGuid>62bb370a-2704-46f3-90a9-cfcd951e602f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='application-Material-manageStock-component---S1--idCurrentStockButton-application-Material-manageStock-component---S1--idStorageLocationTable-0-img']</value>
      <webElementGuid>8b0cb249-8fed-4b02-84ce-75291e33bf67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='application-Material-manageStock-component---S1--idCurrentStockButton-application-Material-manageStock-component---S1--idStorageLocationTable-0-inner']/span</value>
      <webElementGuid>dbd56cc3-3af4-4f08-bbb6-ce2b45ee34a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/button/span/span</value>
      <webElementGuid>1519e54e-e95f-4ff3-a820-4ece605ba83a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'application-Material-manageStock-component---S1--idCurrentStockButton-application-Material-manageStock-component---S1--idStorageLocationTable-0-img']</value>
      <webElementGuid>6acb4d57-4e24-49a8-92fc-ada149ea16e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
