<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_MZ-FG-EB01</name>
   <tag></tag>
   <elementGuidId>c94d11d6-c8c7-4b87-b432-4c67c9f4c06b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.sapMInputHighlight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__label3-application-Material-manageStock-component---S1--idMaterialInput-0']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e250a78d-1c20-4136-b97b-49f64a3c09ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputHighlight</value>
      <webElementGuid>ab848e79-f80b-4495-85dc-94008071cfa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MZ-FG-EB01</value>
      <webElementGuid>ae7428ea-5a64-4a3e-ba92-98752096dfd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__label3-application-Material-manageStock-component---S1--idMaterialInput-0&quot;)/span[@class=&quot;sapMInputHighlight&quot;]</value>
      <webElementGuid>c304b55e-25e9-461c-a8b4-0d26d26bf571</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='__label3-application-Material-manageStock-component---S1--idMaterialInput-0']/span</value>
      <webElementGuid>e44fd2f1-440d-46b0-9525-2a7627809d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::span[3]</value>
      <webElementGuid>04aff35a-b611-469b-b46a-ebb57a5b7605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batch'])[1]/following::span[6]</value>
      <webElementGuid>ac6e5e6e-c696-4e69-95c7-5b57d5054914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E BIKE'])[1]/preceding::span[2]</value>
      <webElementGuid>b9356f14-e174-45aa-b933-4497d35a8689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MZ-FG-EB01']/parent::*</value>
      <webElementGuid>b197f65b-b857-43b2-b082-9fd6b6e94268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/span/span</value>
      <webElementGuid>607b7fb2-af88-4958-9fab-034fd8ea4ab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'MZ-FG-EB01' or . = 'MZ-FG-EB01')]</value>
      <webElementGuid>221b4d32-eb47-46f9-80f1-0e22df35ea15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
