<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Initial Entry_idManageStockType-arrow</name>
   <tag></tag>
   <elementGuidId>794f205c-bc6a-43d9-befa-2f85888db25b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#idManageStockType-arrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='idManageStockType-arrow']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d73f83d1-cf3b-4d0d-b7e2-54dd5bb29676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idManageStockType-arrow</value>
      <webElementGuid>f948e0ab-5214-4623-9fe2-64feaea6a34e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d61626a3-62ea-4110-8481-d6652c774f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMSltArrow sapMSltArrowState</value>
      <webElementGuid>9a4395b0-4fb4-4bff-9c1b-42d163ef7a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idManageStockType-arrow&quot;)</value>
      <webElementGuid>f7041c97-34b0-42e2-9a74-0a8e34130c00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='idManageStockType-arrow']</value>
      <webElementGuid>b3d4502d-81fe-4399-b5ca-0210a5c11acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idManageStockType']/span[2]</value>
      <webElementGuid>91b378d8-4354-48ed-9f53-9ff970a0a4dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span[2]</value>
      <webElementGuid>fe7c3638-39c4-4f76-859c-7d3ca4b22365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'idManageStockType-arrow']</value>
      <webElementGuid>d7fa2bb7-767c-4198-b5ec-4abaac7e71c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
