<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Plant 1 US</name>
   <tag></tag>
   <elementGuidId>243dac95-e3ba-4a38-b238-a357639a8135</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='Plant 1 US']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__item26-titleText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7f398e7c-ecd6-40c0-aa81-a3f0323f9715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputHighlight</value>
      <webElementGuid>d780dcf4-74d7-4f82-9be1-ce1a633362f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Plant 1 US</value>
      <webElementGuid>f5d7a2de-0a2a-4e34-ab37-17c79860dd50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__item26-titleText&quot;)</value>
      <webElementGuid>5f43d5c0-414a-48ab-b4d6-dad430824de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__item26-titleText</value>
      <webElementGuid>5f1a8e8f-474a-4162-9ac9-7f5255c1403c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>a8241fbf-8085-419f-8241-8b078635b5f8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
