<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_203860</name>
   <tag></tag>
   <elementGuidId>767c341a-680f-463f-a016-926744440436</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__identifier0-__clone211-__clone218-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='__identifier0-__clone211-__clone218-link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c22ca5e3-aae3-4577-95ee-bc1c9c4b8097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__identifier0-__clone211-__clone218-link</value>
      <webElementGuid>cdf10d4e-4716-42a8-b263-91b79ad21c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__identifier0-__clone211-__clone218-link</value>
      <webElementGuid>773297ec-23c9-4e7c-a6db-f59e9d03a818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>4daf6862-b376-47de-950a-7536f38ef5d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bd4b4db3-0b89-4035-872e-ab40d889c064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>__text124 __identifier0-__clone211-__clone218-text cus.sd.salesorderv2.manage::SalesOrderManageList--fe::table::SalesOrderManage::LineItem::C::SalesOrder __label8 __identifier0-__clone211-__clone218-link</value>
      <webElementGuid>0f6bc4c1-530a-416e-a74b-90929232ecf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMLnk sapMLnkMaxWidth</value>
      <webElementGuid>77616090-cb12-4b0b-b07c-c92e963b6980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>203860</value>
      <webElementGuid>a6bf3468-35ec-44cd-8871-c65cd4fbf959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__identifier0-__clone211-__clone218-link&quot;)</value>
      <webElementGuid>034e0d8e-3b71-4ce3-bfaf-1f9063418b69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='__identifier0-__clone211-__clone218-link']</value>
      <webElementGuid>b8ee22ac-df95-4d99-ac6f-d5c17e904bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__identifier0-__clone211-__clone218-title']/a</value>
      <webElementGuid>7e924343-c81b-4dae-8456-582852317c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'203860')]</value>
      <webElementGuid>506ad096-946d-4577-9b1b-6098ab6279fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>aa24bf39-1f94-4dcc-acf6-5c21c50fdb6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>a07bb7a7-2b7b-480a-a977-d8803cc82efc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '__identifier0-__clone211-__clone218-link' and @href = '#' and (text() = '203860' or . = '203860')]</value>
      <webElementGuid>11806349-91ec-4a84-afce-971e3e6e3558</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
