<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bigmart (USCU_L09)</name>
   <tag></tag>
   <elementGuidId>cce5eb1a-f9f4-48d9-836a-5b70a2f6f31b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__link27-__clone212-__clone218</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='__link27-__clone212-__clone218']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>49b80e40-f240-4c71-b9b5-c7ceb60d0dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__link27-__clone212-__clone218</value>
      <webElementGuid>f9992659-50c4-41ac-a1b0-51e9874fc63a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__link27-__clone212-__clone218</value>
      <webElementGuid>60a84765-211d-4d09-9330-13d99600dedf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>97a08bce-f772-4860-a8d7-c9140e930a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>22b78b3f-2616-47d8-9328-b14df685bacd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>__label10 __link27-__clone212-__clone218</value>
      <webElementGuid>423d9726-7f2e-4f49-a3ec-9cac7fe85674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMLnk sapMLnkWrapping sapMLnkMaxWidth</value>
      <webElementGuid>e6501d21-9cf2-4725-8aef-7782c58b9b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bigmart (USCU_L09)</value>
      <webElementGuid>556e20e9-61c2-4511-9722-b91d5a062de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__link27-__clone212-__clone218&quot;)</value>
      <webElementGuid>db580180-7946-49ba-ab35-2c5f1c5e9355</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='__link27-__clone212-__clone218']</value>
      <webElementGuid>1b7365b3-01af-47af-9064-7cd969cef5fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='cus.sd.salesorderv2.manage::SalesOrderManageList--fe::table::SalesOrderManage::LineItem-innerTableRow-__clone218_cell1']/a</value>
      <webElementGuid>053d25c8-7209-49be-96e3-6c20a203e2e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Bigmart (USCU_L09)')]</value>
      <webElementGuid>e15a7404-f206-4a00-afd2-9face4863f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[3]</value>
      <webElementGuid>9bbb2eb4-9444-4d44-8466-f31e98098dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/a</value>
      <webElementGuid>1af69411-c123-4c92-8392-299a7e369be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '__link27-__clone212-__clone218' and @href = '#' and (text() = 'Bigmart (USCU_L09)' or . = 'Bigmart (USCU_L09)')]</value>
      <webElementGuid>a53679b4-4319-46f4-9072-5f433a8af644</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
