<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Completed</name>
   <tag></tag>
   <elementGuidId>848f5b96-6e4b-4eb8-9116-bc0ea3ecaabd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cus.sd.salesorderv2.manage::SalesOrderManageList--OverallStatus--overallStatusLink-__clone215-__clone218']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4d1d56a5-c0d5-4d7b-b1d3-80e1879baddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cus.sd.salesorderv2.manage::SalesOrderManageList--OverallStatus--overallStatusLink-__clone215-__clone218</value>
      <webElementGuid>6e54f0e7-cace-4bb8-bb87-4d58536e3ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>cus.sd.salesorderv2.manage::SalesOrderManageList--OverallStatus--overallStatusLink-__clone215-__clone218</value>
      <webElementGuid>32cb4202-c08d-4d82-98b1-f35447c690a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>0fa95675-1fad-4713-85c8-9f19d36ea8f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1eafe529-fce5-41ea-85c5-d512a6e9b94c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMLnk sapMLnkMaxWidth</value>
      <webElementGuid>79edc604-b9b6-40d8-af0f-6d0fdb7b4eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Completed</value>
      <webElementGuid>d1a9e51a-cbdc-467f-8f93-83073c16944a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cus.sd.salesorderv2.manage::SalesOrderManageList--OverallStatus--overallStatusLink-__clone215-__clone218&quot;)</value>
      <webElementGuid>aa0bbbfc-c6fa-4803-b066-25e58154a4a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cus.sd.salesorderv2.manage::SalesOrderManageList--OverallStatus--overallStatusLink-__clone215-__clone218']</value>
      <webElementGuid>01daad28-ebaa-422e-8e21-54ca87aa7298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cus.sd.salesorderv2.manage::SalesOrderManageList--OverallStatus--overallStatusLayout-__clone215-__clone218']/div/a</value>
      <webElementGuid>3bb23e5d-56ba-4dad-bb30-b857d43e7002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Completed')]</value>
      <webElementGuid>97c4d0e2-f2eb-4fb9-9e68-d940d773ba98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[4]</value>
      <webElementGuid>e79b7613-ff03-4545-931f-a94816527342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/div/a</value>
      <webElementGuid>c3ada224-06ac-45ea-8e34-e3a7738b44fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cus.sd.salesorderv2.manage::SalesOrderManageList--OverallStatus--overallStatusLink-__clone215-__clone218' and @href = '#' and (text() = 'Completed' or . = 'Completed')]</value>
      <webElementGuid>bd824ae4-7b6d-4d80-8d61-8715bd025aa1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
