<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Create_1</name>
   <tag></tag>
   <elementGuidId>1d4eaaa8-c951-4fda-8c29-7c2c476cb7e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//bdi[@id='fe::APD_::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.CreateWithSalesOrderType::Action::Ok-BDI-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>79d2827a-85c0-4231-aec7-78efb74d2aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fe::APD_::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.CreateWithSalesOrderType::Action::Ok-BDI-content</value>
      <webElementGuid>b8195a10-a03a-45e2-8958-7be73faac1d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>a9861d3e-556c-43cb-b970-70ca37eaaa9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>6883fd50-6790-4f59-a4e2-c861f481cea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fe::APD_::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.CreateWithSalesOrderType::Action::Ok-BDI-content&quot;)</value>
      <webElementGuid>55abcf30-e253-41b6-978c-b839d594df69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='fe::APD_::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.CreateWithSalesOrderType::Action::Ok-BDI-content']</value>
      <webElementGuid>af25bec0-7c62-46ff-be80-7749bbf0cfdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='fe::APD_::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.CreateWithSalesOrderType::Action::Ok-content']/bdi</value>
      <webElementGuid>f9f86a0e-ee5b-4145-8200-ee77d8df7c8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/bdi</value>
      <webElementGuid>bd33c420-0e2c-47a3-b9e4-7e18bd69458b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = 'fe::APD_::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.CreateWithSalesOrderType::Action::Ok-BDI-content' and (text() = 'Create' or . = 'Create')]</value>
      <webElementGuid>20b505e4-0463-4253-b857-0173f4adcad4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
