<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Create</name>
   <tag></tag>
   <elementGuidId>63392142-e7f6-4cb2-8198-d9c0485d910b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//bdi[@id='cus.sd.salesorderv2.manage::SalesOrderManageList--fe::table::SalesOrderManage::LineItem::DataFieldForAction::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.CreateWithSalesOrderType::Collection::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.SalesOrderManageType-BDI-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>98260b30-b98e-42bf-b304-08f5ecae4ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cus.sd.salesorderv2.manage::SalesOrderManageList--fe::table::SalesOrderManage::LineItem::DataFieldForAction::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.CreateWithSalesOrderType::Collection::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.SalesOrderManageType-BDI-content</value>
      <webElementGuid>76f415c1-23f2-486d-a96d-ef3dbdff4370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>13aa4b05-2ace-473d-b422-fe8db8b46d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>a1192da3-2443-46ce-a328-b76378946463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cus.sd.salesorderv2.manage::SalesOrderManageList--fe::table::SalesOrderManage::LineItem::DataFieldForAction::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.CreateWithSalesOrderType::Collection::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.SalesOrderManageType-BDI-content&quot;)</value>
      <webElementGuid>43ceed91-3520-4f1f-89a9-e857225fb504</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='cus.sd.salesorderv2.manage::SalesOrderManageList--fe::table::SalesOrderManage::LineItem::DataFieldForAction::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.CreateWithSalesOrderType::Collection::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.SalesOrderManageType-BDI-content']</value>
      <webElementGuid>73335737-d787-4b9d-afe5-1698134697cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cus.sd.salesorderv2.manage::SalesOrderManageList--fe::table::SalesOrderManage::LineItem::DataFieldForAction::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.CreateWithSalesOrderType::Collection::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.SalesOrderManageType-content']/bdi</value>
      <webElementGuid>a79a5e80-fd50-4d92-b01c-508bdb54d494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/button/span/span/bdi</value>
      <webElementGuid>658e5182-1087-4279-affd-27f44106698c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = 'cus.sd.salesorderv2.manage::SalesOrderManageList--fe::table::SalesOrderManage::LineItem::DataFieldForAction::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.CreateWithSalesOrderType::Collection::com.sap.gateway.srvd.c_salesordermanage_sd.v0001.SalesOrderManageType-BDI-content' and (text() = 'Create' or . = 'Create')]</value>
      <webElementGuid>f56e8352-e163-4ebd-8cf5-245be0e8d007</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
