<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divcus.sd.salesorderv2.manageSalesOrderMana_63587b</name>
   <tag></tag>
   <elementGuidId>727329ca-f0ca-4c6c-b7c0-535acd2c65fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cus.sd.salesorderv2.manage::SalesOrderManageList--fe::FilterBar::SalesOrderManage::BasicSearchField-inner-search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a745b1ad-a511-4c6e-810f-5cda309a831b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cus.sd.salesorderv2.manage::SalesOrderManageList--fe::FilterBar::SalesOrderManage::BasicSearchField-inner-search</value>
      <webElementGuid>e022ef17-3fa6-488d-a644-1a31ba118119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a2a1826d-4a97-41b1-b286-72b2585e9b35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMSFS sapMSFB</value>
      <webElementGuid>6cc58774-6764-4551-8945-5060cf22aa5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cus.sd.salesorderv2.manage::SalesOrderManageList--fe::FilterBar::SalesOrderManage::BasicSearchField-inner-search&quot;)</value>
      <webElementGuid>9f43b6bb-877a-478f-81db-9bf73daae832</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cus.sd.salesorderv2.manage::SalesOrderManageList--fe::FilterBar::SalesOrderManage::BasicSearchField-inner-search']</value>
      <webElementGuid>281967c8-81e6-40bd-b4a7-cf281f656e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='cus.sd.salesorderv2.manage::SalesOrderManageList--fe::FilterBar::SalesOrderManage::BasicSearchField-inner-F']/div[2]</value>
      <webElementGuid>6704f366-cb2c-4384-8b8f-d7f58498a65d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]</value>
      <webElementGuid>d6670f6c-bd4d-4854-9ce0-cd30543158b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cus.sd.salesorderv2.manage::SalesOrderManageList--fe::FilterBar::SalesOrderManage::BasicSearchField-inner-search']</value>
      <webElementGuid>2cd97cc6-f3cd-4379-b37a-adbee4e78b2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
