<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputcus.sd.salesorderv2.manageSalesOrderMa_39bb16</name>
   <tag></tag>
   <elementGuidId>83e9c093-1fda-438a-9e0d-003eef520152</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cus.sd.salesorderv2.manage::SalesOrderManageList--fe::FilterBar::SalesOrderManage::BasicSearchField-inner-I']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9f0ab36-f3a9-4d50-9ce0-521033de67c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cus.sd.salesorderv2.manage::SalesOrderManageList--fe::FilterBar::SalesOrderManage::BasicSearchField-inner-I</value>
      <webElementGuid>376764ed-d241-4be0-904c-45114cedb3a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>299748e7-d26e-4a1b-ae8b-72ebef064b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>4a2acd8c-9d4e-4fa3-be52-6bd27b14dbad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ebfec5ed-d2e3-4fe6-b8c8-e2dae11fb706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>f0d1380b-7a01-4db3-89da-d563311ac92a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__text130</value>
      <webElementGuid>2e1ec384-7674-4ea3-a8fd-367fcfc4eac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMSFI</value>
      <webElementGuid>53710b46-dc6c-40bd-9cdd-18ccd55665fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cus.sd.salesorderv2.manage::SalesOrderManageList--fe::FilterBar::SalesOrderManage::BasicSearchField-inner-I&quot;)</value>
      <webElementGuid>4455702f-9844-420f-98f5-69422a27c767</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cus.sd.salesorderv2.manage::SalesOrderManageList--fe::FilterBar::SalesOrderManage::BasicSearchField-inner-I']</value>
      <webElementGuid>fdad64c0-3ca1-4389-98a0-7538a8b07d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='cus.sd.salesorderv2.manage::SalesOrderManageList--fe::FilterBar::SalesOrderManage::BasicSearchField-inner-F']/input</value>
      <webElementGuid>4b78ff30-f887-4737-b4cf-cff5d15e342c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>c191f236-568f-4110-a3e1-a19ccc164215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cus.sd.salesorderv2.manage::SalesOrderManageList--fe::FilterBar::SalesOrderManage::BasicSearchField-inner-I' and @type = 'search' and @placeholder = 'Search']</value>
      <webElementGuid>91f219a8-157a-4577-a74f-a8e2975c57a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
