<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Standard Order (OR)</name>
   <tag></tag>
   <elementGuidId>1a118f6a-a435-4169-aeff-468d8850bfa1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//*[text() = 'Standard Order (OR)' or . = 'Standard Order (OR)'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__text142-__clone401</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bb473317-510b-4e94-b582-0f5958288d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__text142-__clone401</value>
      <webElementGuid>3960e30d-22d3-4b67-acc3-31205dad345d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__text142-__clone401</value>
      <webElementGuid>cedb557b-7f72-423e-97c9-9a8ce9b6ef22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>aac2d5da-5440-4ddd-9d93-3cbc45d54939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMText sapUiSelectable sapMTextMaxWidth sapMTextRenderWhitespaceWrap</value>
      <webElementGuid>ca2459e4-05e9-4b7b-b216-fc33f5b12f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Standard Order (OR)</value>
      <webElementGuid>118b44be-4879-4fa3-beb8-9ffd50e3aabf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__text142-__clone401&quot;)</value>
      <webElementGuid>5e6b0841-88f6-4bfe-9292-8736f050943a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
