<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>spanAPD_SalesOrderType-inner-vhi</name>
   <tag></tag>
   <elementGuidId>92f7881b-9355-42ec-a098-f20bc5c9ccc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='APD_::SalesOrderType-inner-vhi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c7c76010-3422-43f1-b053-b6cef99bf333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>APD_::SalesOrderType-inner-vhi</value>
      <webElementGuid>5bcb958f-c193-48ad-93f1-5af2743053a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>APD_::SalesOrderType-inner-vhi</value>
      <webElementGuid>d1d77c5c-028f-4f48-b54f-c55ff5ce2cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6b2fe43e-928a-420c-80ed-d7f23ca8258e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Show Value Help</value>
      <webElementGuid>87560e3b-2ddd-472b-8c69-93578f13518c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-icon-content</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>2c19f54c-a0f4-4c60-9501-5ec2a918f05d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiIcon sapUiIconMirrorInRTL sapUiIconPointer sapMInputBaseIcon</value>
      <webElementGuid>6e0071c1-a89b-49c8-8e00-eb554d65a2fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;APD_::SalesOrderType-inner-vhi&quot;)</value>
      <webElementGuid>a03ffbc3-0469-4c01-a323-ba091f462a99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='APD_::SalesOrderType-inner-vhi']</value>
      <webElementGuid>435e054e-ded1-4046-a208-f876c5c83d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='APD_::SalesOrderType-inner-content']/div/span</value>
      <webElementGuid>31f88e8a-2073-4c7c-b138-681a093799f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div/div/div/div/span</value>
      <webElementGuid>95dae8fe-6b36-4d86-81f7-6ce0bc1c5912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'APD_::SalesOrderType-inner-vhi']</value>
      <webElementGuid>955d5d5c-1149-43d9-a984-1dbd42dbdd98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
