<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Order to Cash</name>
   <tag></tag>
   <elementGuidId>4b708c95-6cda-4c05-98e4-b8b69d3e9cdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__title4-__list8-2-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__title4-__list8-2-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>39938f56-0c08-41f7-8cbb-b4efd072b8b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__title4-__list8-2-inner</value>
      <webElementGuid>75a06bd0-281e-4157-b048-0d4b343fa387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>d8a9aa18-4b71-4982-bb36-fcd3ac4c08c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Order to Cash</value>
      <webElementGuid>799cde64-f75e-489f-9716-d1b454a34291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__title4-__list8-2-inner&quot;)</value>
      <webElementGuid>47c151b5-eeaa-4cab-a209-59edf8c07058</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__title4-__list8-2-inner']</value>
      <webElementGuid>8d170376-8c6e-4ed0-9552-a3ceb361173b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__title4-__list8-2']/span</value>
      <webElementGuid>2f5f1338-2b01-4b86-a38a-ddb846a105b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div/div/div[2]/div/ul/li[3]/div/div/div/div[2]/div/span</value>
      <webElementGuid>890489ea-ead9-4637-a85b-053e9c019b17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__title4-__list8-2-inner' and (text() = 'Order to Cash' or . = 'Order to Cash')]</value>
      <webElementGuid>4f0f86be-0872-4cd5-8ee0-bee21a9de654</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
