<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Go</name>
   <tag></tag>
   <elementGuidId>4d4c64bb-63bb-4baa-909d-2c97f24f2fb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Go']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-BillingDocument-create-component---worklist--smartFilterBar-btnGo-BDI-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>11775b5f-6201-4334-8d20-87bf520602b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-BillingDocument-create-component---worklist--smartFilterBar-btnGo-BDI-content</value>
      <webElementGuid>66e8676d-1dd0-411d-8ca7-3ddbe5214b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>b423b252-e692-4751-b911-206f467af3a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go</value>
      <webElementGuid>a417f0ea-cb0d-49fa-a514-17456c03abb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-BillingDocument-create-component---worklist--smartFilterBar-btnGo-BDI-content&quot;)</value>
      <webElementGuid>e14622e3-d0b4-41c8-b137-15fc5b786799</webElementGuid>
   </webElementProperties>
</WebElementEntity>
