<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Create Billing Documents</name>
   <tag></tag>
   <elementGuidId>c89fa6c0-179b-4092-8a84-ccbdc56ca489</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-BillingDocument-create-component---worklist--createButton-BDI-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//bdi[@id='application-BillingDocument-create-component---worklist--createButton-BDI-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>fdc067a3-8339-4715-83c5-c1681bcd2697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-BillingDocument-create-component---worklist--createButton-BDI-content</value>
      <webElementGuid>f41eff4c-e755-4337-be5e-87ef3cac0e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>9659c5a1-1c93-400d-971d-f0e0d61b6b35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Billing Documents</value>
      <webElementGuid>200b0f5c-6dba-4568-b132-de02a8d6a60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-BillingDocument-create-component---worklist--createButton-BDI-content&quot;)</value>
      <webElementGuid>52631296-1c04-4979-a1f7-76b476eee985</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='application-BillingDocument-create-component---worklist--createButton-BDI-content']</value>
      <webElementGuid>48275299-5dae-4451-b36b-07ce3a68edf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='application-BillingDocument-create-component---worklist--createButton-content']/bdi</value>
      <webElementGuid>01926363-a04e-449d-bfc7-ad42cd86aeae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing Due List Items (1)'])[1]/following::bdi[1]</value>
      <webElementGuid>63608d18-5e0b-4232-a07b-ba9c58dd3689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pin Header'])[1]/following::bdi[1]</value>
      <webElementGuid>abec8db3-b2a0-44a1-a3b9-c7171c453891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing Settings'])[1]/preceding::bdi[1]</value>
      <webElementGuid>a194cbb0-c70e-45b7-818a-fc3af52995c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing Settings'])[2]/preceding::bdi[2]</value>
      <webElementGuid>4035e349-4dde-4354-9a87-bf5c6fd1870d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/button/span/span/bdi</value>
      <webElementGuid>e5f291fd-cd67-48fb-8e1a-fc0c77fb5da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = 'application-BillingDocument-create-component---worklist--createButton-BDI-content' and (text() = 'Create Billing Documents' or . = 'Create Billing Documents')]</value>
      <webElementGuid>c4e70c27-001e-4279-b330-914897528a65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
