<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SD Document_application-BillingDocume_2871f6</name>
   <tag></tag>
   <elementGuidId>0cfd276c-5f5a-4558-ab53-e8c52275ca5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-BillingDocument-create-component---worklist--smartFilterBar-filterItemControl_BASIC-ReferenceSDDocument-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='application-BillingDocument-create-component---worklist--smartFilterBar-filterItemControl_BASIC-ReferenceSDDocument-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8dc2031e-bb1e-4347-b7d3-fb2aa98d633f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-BillingDocument-create-component---worklist--smartFilterBar-filterItemControl_BASIC-ReferenceSDDocument-inner</value>
      <webElementGuid>d8178f42-f58c-4866-ab10-54b50c210b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>application-BillingDocument-create-component---worklist--smartFilterBar-filterItem-___INTERNAL_-ReferenceSDDocument</value>
      <webElementGuid>c40239d4-a4c2-47dd-b24a-f7fc247418e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__text83 __text122</value>
      <webElementGuid>60e38f3b-33df-4d27-b262-cf96e1fe2df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>10350608-500c-454e-9401-70249aeafd99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-roledescription</name>
      <type>Main</type>
      <value>Multi Value Input</value>
      <webElementGuid>30df6ce0-b0a4-427a-b755-e8870e2d9168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e837cf82-ef11-436e-9190-a5167568cd85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>043bbee1-ab81-4a54-8fa3-faed782201f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>8bb4798b-58bb-4264-b030-3847b1dc89c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-BillingDocument-create-component---worklist--smartFilterBar-filterItemControl_BASIC-ReferenceSDDocument-inner&quot;)</value>
      <webElementGuid>1abbf27a-d5a7-4eba-a1dc-e4cc7fdc94bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='application-BillingDocument-create-component---worklist--smartFilterBar-filterItemControl_BASIC-ReferenceSDDocument-inner']</value>
      <webElementGuid>abf84479-1585-481b-9031-a6659e58b061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-BillingDocument-create-component---worklist--smartFilterBar-filterItemControl_BASIC-ReferenceSDDocument-content']/input</value>
      <webElementGuid>3d5042a9-36ea-4303-90e0-0b18ff51e05e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>a2eff17c-e649-4730-afba-6a448513ff03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'application-BillingDocument-create-component---worklist--smartFilterBar-filterItemControl_BASIC-ReferenceSDDocument-inner' and @type = 'text']</value>
      <webElementGuid>31b4d41a-ec9f-466e-b329-5a6c9c7e92f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
