<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_80204582</name>
   <tag></tag>
   <elementGuidId>5db127da-56d9-4d3f-859c-5a4f8786ffd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-BillingDocument-create-component---worklist--referenceSDDocumentCategoryColumnListItem-__clone209_cell0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='application-BillingDocument-create-component---worklist--referenceSDDocumentCategoryColumnListItem-__clone209_cell0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>3b500c2d-d906-42dd-8f9a-7c719f8512ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-BillingDocument-create-component---worklist--referenceSDDocumentCategoryColumnListItem-__clone209_cell0</value>
      <webElementGuid>71e773b9-e309-43b1-8e74-3ab4e5f127ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-column</name>
      <type>Main</type>
      <value>application-BillingDocument-create-component---worklist--referenceSDDocumentCol</value>
      <webElementGuid>6d255482-9faf-42ce-a683-c0bdfc633ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>headers</name>
      <type>Main</type>
      <value>application-BillingDocument-create-component---worklist--referenceSDDocumentCol</value>
      <webElementGuid>bcef6490-276c-45d1-8327-f629956970bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMListTblCell</value>
      <webElementGuid>d1ae46b2-1713-4d85-82da-c257a5950de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>80204582</value>
      <webElementGuid>1b36652e-14fe-4976-91e5-3f0b5fe8557d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-BillingDocument-create-component---worklist--referenceSDDocumentCategoryColumnListItem-__clone209_cell0&quot;)</value>
      <webElementGuid>9427fa81-2c05-4aae-b040-f37a40dc39bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='application-BillingDocument-create-component---worklist--referenceSDDocumentCategoryColumnListItem-__clone209_cell0']</value>
      <webElementGuid>283dfa40-4606-463a-9251-83515ab05551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='application-BillingDocument-create-component---worklist--referenceSDDocumentCategoryColumnListItem-__clone209']/td[3]</value>
      <webElementGuid>4e7c7a72-1baf-4d0b-a2fd-f6a0f22c35fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Net Value'])[1]/following::td[3]</value>
      <webElementGuid>f476b91d-7427-47a8-bf22-5e21d731052d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing Date'])[2]/following::td[3]</value>
      <webElementGuid>e7ca6b1d-ce7f-45e3-88cc-533d79f6df5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery'])[1]/preceding::td[1]</value>
      <webElementGuid>4c9f9dcb-3581-4b97-a8b9-b78f56852b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USD'])[1]/preceding::td[4]</value>
      <webElementGuid>3a9d4cf5-9a86-4940-ad44-ce0858dacfec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]</value>
      <webElementGuid>9d6c2313-6fd2-4a52-a274-c45541030fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'application-BillingDocument-create-component---worklist--referenceSDDocumentCategoryColumnListItem-__clone209_cell0' and (text() = '80204582' or . = '80204582')]</value>
      <webElementGuid>f0c89c07-fd1e-4deb-92ed-d934d856d9c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
