<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_SkyBikes Inc. (17100002)</name>
   <tag></tag>
   <elementGuidId>840b8d25-d64b-45cf-9f60-99e665f0f256</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-BillingDocument-create-component---worklist--referenceSDDocumentCategoryColumnListItem-__clone213_cell3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='application-BillingDocument-create-component---worklist--referenceSDDocumentCategoryColumnListItem-__clone213_cell3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>4fabc60e-237d-4c9a-8bc7-6ee7b4a60b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-BillingDocument-create-component---worklist--referenceSDDocumentCategoryColumnListItem-__clone213_cell3</value>
      <webElementGuid>9f427d0f-0b4d-40e9-8c94-ffa1a3628b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-column</name>
      <type>Main</type>
      <value>application-BillingDocument-create-component---worklist--smartTable-SoldToParty</value>
      <webElementGuid>7b789076-632d-4469-9856-57d623b6f3c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>headers</name>
      <type>Main</type>
      <value>application-BillingDocument-create-component---worklist--smartTable-SoldToParty</value>
      <webElementGuid>0547ef5d-b917-49be-8e80-6d4d7215711a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMListTblCell</value>
      <webElementGuid>408a584e-43d4-468e-bf54-c7a2a30eb7c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SkyBikes Inc. (17100002)</value>
      <webElementGuid>442fb9db-3c76-405d-9336-9c7467a622d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-BillingDocument-create-component---worklist--referenceSDDocumentCategoryColumnListItem-__clone213_cell3&quot;)</value>
      <webElementGuid>02d481f0-eb2d-4751-ac1f-3a44e92b50f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='application-BillingDocument-create-component---worklist--referenceSDDocumentCategoryColumnListItem-__clone213_cell3']</value>
      <webElementGuid>f04c93c4-def1-4a62-8740-a94d4cbf5b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='application-BillingDocument-create-component---worklist--referenceSDDocumentCategoryColumnListItem-__clone213']/td[5]</value>
      <webElementGuid>21982b38-e7bc-4aeb-89b2-71c3fb96e0e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order'])[2]/following::td[1]</value>
      <webElementGuid>2c0a1803-3bb0-4f9a-b72c-7cf8f48884c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USD'])[4]/following::td[8]</value>
      <webElementGuid>e543f5f2-afbd-4c8c-921d-60078a6de3c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USD'])[5]/preceding::td[2]</value>
      <webElementGuid>a0c8a955-10b2-4c89-adec-a62e9e79d892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order'])[3]/preceding::td[9]</value>
      <webElementGuid>c8ee8fd6-bf3f-4d11-bc42-2c49924a7621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[5]</value>
      <webElementGuid>7bf564be-0fbb-4520-8fc9-4f201047c754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'application-BillingDocument-create-component---worklist--referenceSDDocumentCategoryColumnListItem-__clone213_cell3' and (text() = 'SkyBikes Inc. (17100002)' or . = 'SkyBikes Inc. (17100002)')]</value>
      <webElementGuid>53be6025-0224-4b70-81b5-3ad75fbb5d27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
