<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__shell-header-icon</name>
   <tag></tag>
   <elementGuidId>0641bb3f-9530-447c-b068-bc6e24068129</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#shell-header-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='shell-header-icon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9119da33-89bd-43fe-a7ca-a2379edacb00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shell-header-icon</value>
      <webElementGuid>abc0db0e-d203-4113-91c4-ab871eb51fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>SAP Logo</value>
      <webElementGuid>ab687d42-3de6-43d6-8675-4f38603d4677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ui5.sap.com/1.114.9/resources/sap/ushell/themes/base/img/SAPLogo.svg</value>
      <webElementGuid>63fa2d42-0afe-4415-9618-8720b12c79f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shell-header-icon&quot;)</value>
      <webElementGuid>d7e780c0-e22b-4175-9db1-0fe0c63e721b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='shell-header-icon']</value>
      <webElementGuid>7e6675b1-b1aa-4be2-ac4a-01e8cedafb0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='shell-header-logo']/img</value>
      <webElementGuid>8eed74c7-2f87-446b-84a2-07f11007d671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='SAP Logo']</value>
      <webElementGuid>92d449db-25c8-4d1d-a7eb-81b873de3139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>ce97ebb5-b886-43e9-9738-42cc8663a1d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'shell-header-icon' and @alt = 'SAP Logo' and @src = 'https://ui5.sap.com/1.114.9/resources/sap/ushell/themes/base/img/SAPLogo.svg']</value>
      <webElementGuid>cae079aa-2675-4a6e-8a91-f0cfa0167142</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
