<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Delivery___xmlview109--S1ReferenceDoc_97d248</name>
   <tag></tag>
   <elementGuidId>13080342-155f-4c8e-ac12-1d3dedbb2ae6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//bdi[text()='Delivery']/following::input[@class='sapMInputBaseInner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__xmlview109--S1ReferenceDocumentInput-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b67896c-0581-43c0-ba58-bff3b8e6ae4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__xmlview109--S1ReferenceDocumentInput-inner</value>
      <webElementGuid>2eaeaec5-64f7-43e0-b4eb-4ebe24b0de44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>27bb6fe9-8fd4-492c-954c-8522bdf5dc6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>__xmlview109--S1PickDeliveryLabel</value>
      <webElementGuid>0a57aafe-cf43-4789-ba85-4d00eb9ab705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__text83</value>
      <webElementGuid>6a6aec41-7b8c-45cb-86e1-1b34cae25e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8798490b-594d-486a-96ce-2ced9b804dbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>47651d2e-86e9-4240-be34-97030303505e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>587f53e0-7360-4eb2-aae8-4f7dbed72aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__xmlview109--S1ReferenceDocumentInput-inner&quot;)</value>
      <webElementGuid>28a3b287-fbc1-4560-b63c-a6273c9950fa</webElementGuid>
   </webElementProperties>
</WebElementEntity>
