<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirmation Status___xmlview109--S1P_099f61</name>
   <tag></tag>
   <elementGuidId>91305c8e-b7c5-4385-bc95-4c9640c7dd0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='Picking Quantity']/following::input[contains(@id,'PickedQuantityInput')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__xmlview109--S1PickedQuantityInput-__xmlview109--S1DeliveryItemsTable-0-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d120bba5-0c31-4fb6-be20-58199cf521af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__xmlview109--S1PickedQuantityInput-__xmlview109--S1DeliveryItemsTable-0-inner</value>
      <webElementGuid>c8eef22f-5450-467d-9769-d906720faa82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>c2748c9f-14cc-41ef-97bb-36fa5ad8c0df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7cd51a7d-d5d2-4e24-aae9-708ea19c17fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>__text90</value>
      <webElementGuid>2f007e7b-a25a-428b-8afd-3890e8b70dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__xmlview109--S1PickedQuantityInput-__xmlview109--S1DeliveryItemsTable-0-descr</value>
      <webElementGuid>3e3cf0c0-90f1-441c-8311-f2958492829c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>54e0585c-6bba-4c0d-a04a-bf9ed0e7d027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8c89c01c-9926-4ff3-b2eb-1bc9913f7e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>6fcf788d-b366-4039-b73c-326707c6caed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__xmlview109--S1PickedQuantityInput-__xmlview109--S1DeliveryItemsTable-0-inner&quot;)</value>
      <webElementGuid>908f4ab9-e635-4860-aadd-bb4e561ad099</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__xmlview109--S1PickedQuantityInput-__xmlview109--S1DeliveryItemsTable-0-inner']</value>
      <webElementGuid>7a557534-a33b-4e2a-987c-0179703d47d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__xmlview109--S1PickedQuantityInput-__xmlview109--S1DeliveryItemsTable-0-content']/input</value>
      <webElementGuid>dbce3fbb-0573-48f5-98cc-b8a4224d2ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div/div/input</value>
      <webElementGuid>cc608e59-2770-468d-8b7d-cd0664b699fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '__xmlview109--S1PickedQuantityInput-__xmlview109--S1DeliveryItemsTable-0-inner' and @type = 'text']</value>
      <webElementGuid>0a5192d1-1a0c-494e-99a7-7f03cede6221</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
